/* WARNING: Automatically generated code.
 * This code has been generated by the DH compiler.
 */
#ifdef HAVE_CONFIG_H
# include "lushconf.h"
#endif

/*
 * LUSH HEADERS
 */
#include "header.h"
#include "dh.h"
#include "idxmac.h"
#include "idxops.h"
#include "check_func.h"
/*
 * USER DEFINED HEADERS
 */
#include "idxsquops.h"



/* ---------------------------------------- */


/*
 * FUNCTION idx-d2timesd2
 */
extern_c struct idx* C_idx_d2timesd2(struct idx* L1_a,struct idx* L1_b,struct idx* L1_c)
{
TRACE_PUSH("C_idx_d2timesd2");
{
struct idx* L_Tmp0;
{
{
RTERR_LOOPDIM((L1_c)->dim[1] != (L1_b)->dim[1]);
Midx_begin_eloop2(L3_bi, L1_b,L3_ci, L1_c,real) {
check_main_main_maout_dot21(L1_a,&L3_bi,&L3_ci);
Midx_m2dotm1(L1_a,&L3_bi,&L3_ci,real,real,real);
} Midx_end_eloop2(L3_bi, L1_b,L3_ci, L1_c,real);
L_Tmp0 = L1_c;
}
}
TRACE_POP("C_idx_d2timesd2");
return L_Tmp0;
}
}

/*
 * FUNCTION idx-d1reverse
 */
extern_c char C_idx_d1reverse(struct idx* L1_vec)
{
TRACE_PUSH("C_idx_d1reverse");
{
char L_Tmp0;
{
real L2_1_n_el;
real L2_2_n_eld1;
real L2_3_half_n_el;
real L2_4_half_d1;
L2_1_n_el = (L1_vec)->dim[0];
L2_2_n_eld1 = (L2_1_n_el-1);
L2_3_half_n_el = (L2_1_n_el/(real)2);
L2_4_half_d1 = (L2_3_half_n_el-1);
{
real L3_5_i;
L3_5_i = 0;
for(;
((1>0)?(L3_5_i<=L2_4_half_d1):(L3_5_i>=L2_4_half_d1));
(L3_5_i)+=1 ) {
{
real L4_6_buffer;
real L4_7_j;
RTERR_BOUND(L3_5_i<0 || L3_5_i>=(L1_vec)->dim[0]);
L4_6_buffer = IDX_PTR(L1_vec,real)[(L1_vec)->mod[0]*((int)L3_5_i)];
L4_7_j = (L2_2_n_eld1-L3_5_i);
RTERR_BOUND(L3_5_i<0 || L3_5_i>=(L1_vec)->dim[0]);
RTERR_BOUND(L4_7_j<0 || L4_7_j>=(L1_vec)->dim[0]);
IDX_PTR(L1_vec,real)[(L1_vec)->mod[0]*((int)L3_5_i)] = IDX_PTR(L1_vec,real)[(L1_vec)->mod[0]*((int)L4_7_j)];
RTERR_BOUND(L4_7_j<0 || L4_7_j>=(L1_vec)->dim[0]);
IDX_PTR(L1_vec,real)[(L1_vec)->mod[0]*((int)L4_7_j)] = L4_6_buffer;
}
}
}
L_Tmp0 = 0;
}
TRACE_POP("C_idx_d1reverse");
return 0;
}
}

/*
 * FUNCTION idx-d1fill
 */
extern_c char C_idx_d1fill(struct idx* L1_m,real L1_c)
{
TRACE_PUSH("C_idx_d1fill");
{
{ register double *mp;
  register int i, jmax = (L1_m)->dim[0];
  register int imat1_m0 = (L1_m)->mod[0];
  mp = IDX_PTR((L1_m),double);
  for (i=0; i <jmax; i++){;
*mp = (L1_c);
    mp += imat1_m0;
  } }
TRACE_POP("C_idx_d1fill");
return 0;
}
}

/*
 * FUNCTION idx-d2fill
 */
extern_c struct idx* C_idx_d2fill(struct idx* L1_m,real L1_v)
{
TRACE_PUSH("C_idx_d2fill");
{
struct idx* L_Tmp0;
{
Midx_begin_bloop1(L2_lm, L1_m,real) {
C_idx_d1fill(&L2_lm, L1_v);
} Midx_end_bloop1(L2_lm, L1_m,real);
L_Tmp0 = L1_m;
}
TRACE_POP("C_idx_d2fill");
return L_Tmp0;
}
}

/*
 * FUNCTION idx-d3fill
 */
extern_c struct idx* C_idx_d3fill(struct idx* L1_m,real L1_v)
{
TRACE_PUSH("C_idx_d3fill");
{
struct idx* L_Tmp0;
{
Midx_begin_bloop1(L2_lm, L1_m,real) {
{
Midx_begin_bloop1(L3_llm, &L2_lm,real) {
C_idx_d1fill(&L3_llm, L1_v);
} Midx_end_bloop1(L3_llm, &L2_lm,real);
}
} Midx_end_bloop1(L2_lm, L1_m,real);
L_Tmp0 = L1_m;
}
TRACE_POP("C_idx_d3fill");
return L_Tmp0;
}
}

/*
 * FUNCTION idx-d1dotc
 */
extern_c char C_idx_d1dotc(struct idx* L1_m,real L1_c,struct idx* L1_o)
{
TRACE_PUSH("C_idx_d1dotc");
{
Msame_size1(L1_m,L1_o); 
{ register double *mp;
  register double *op;
  register int i, jmax = (L1_m)->dim[0];
  register int imat1_m0 = (L1_m)->mod[0];
  register int imat2_m0 = (L1_o)->mod[0];
  mp = IDX_PTR((L1_m),double);
  op = IDX_PTR((L1_o),double);
  for (i=0; i <jmax; i++){;
*op = *mp * (L1_c);
    mp += imat1_m0;
    op += imat2_m0;
  } }
TRACE_POP("C_idx_d1dotc");
return 0;
}
}

/*
 * FUNCTION idx-d2dotc
 */
extern_c struct idx* C_idx_d2dotc(struct idx* L1_m,real L1_f,struct idx* L1_q)
{
TRACE_PUSH("C_idx_d2dotc");
{
struct idx* L_Tmp0;
{
RTERR_LOOPDIM((L1_q)->dim[0] != (L1_m)->dim[0]);
Midx_begin_bloop2(L2_lm, L1_m,L2_lq, L1_q,real) {
C_idx_d1dotc(&L2_lm, L1_f, &L2_lq);
} Midx_end_bloop2(L2_lm, L1_m,L2_lq, L1_q,real);
L_Tmp0 = L1_q;
}
TRACE_POP("C_idx_d2dotc");
return L_Tmp0;
}
}

/*
 * FUNCTION idx-d3dotc
 */
extern_c struct idx* C_idx_d3dotc(struct idx* L1_m,real L1_f,struct idx* L1_q)
{
TRACE_PUSH("C_idx_d3dotc");
{
struct idx* L_Tmp0;
{
RTERR_LOOPDIM((L1_q)->dim[0] != (L1_m)->dim[0]);
Midx_begin_bloop2(L2_lm, L1_m,L2_lq, L1_q,real) {
{
RTERR_LOOPDIM((&L2_lq)->dim[0] != (&L2_lm)->dim[0]);
Midx_begin_bloop2(L3_llm, &L2_lm,L3_llq, &L2_lq,real) {
C_idx_d1dotc(&L3_llm, L1_f, &L3_llq);
} Midx_end_bloop2(L3_llm, &L2_lm,L3_llq, &L2_lq,real);
}
} Midx_end_bloop2(L2_lm, L1_m,L2_lq, L1_q,real);
L_Tmp0 = L1_q;
}
TRACE_POP("C_idx_d3dotc");
return L_Tmp0;
}
}

/*
 * FUNCTION idx-d1dotcacc
 */
extern_c char C_idx_d1dotcacc(struct idx* L1_m,real L1_c,struct idx* L1_o)
{
TRACE_PUSH("C_idx_d1dotcacc");
{
Msame_size1(L1_m,L1_o); 
{ register double *mp;
  register double *op;
  register int i, jmax = (L1_m)->dim[0];
  register int imat1_m0 = (L1_m)->mod[0];
  register int imat2_m0 = (L1_o)->mod[0];
  mp = IDX_PTR((L1_m),double);
  op = IDX_PTR((L1_o),double);
  for (i=0; i <jmax; i++){;
*op += *mp * (L1_c);
    mp += imat1_m0;
    op += imat2_m0;
  } }
TRACE_POP("C_idx_d1dotcacc");
return 0;
}
}

/*
 * FUNCTION idx-d2dotcacc
 */
extern_c struct idx* C_idx_d2dotcacc(struct idx* L1_m,real L1_f,struct idx* L1_q)
{
TRACE_PUSH("C_idx_d2dotcacc");
{
struct idx* L_Tmp0;
{
RTERR_LOOPDIM((L1_q)->dim[0] != (L1_m)->dim[0]);
Midx_begin_bloop2(L2_lm, L1_m,L2_lq, L1_q,real) {
C_idx_d1dotcacc(&L2_lm, L1_f, &L2_lq);
} Midx_end_bloop2(L2_lm, L1_m,L2_lq, L1_q,real);
L_Tmp0 = L1_q;
}
TRACE_POP("C_idx_d2dotcacc");
return L_Tmp0;
}
}

/*
 * FUNCTION idx-d3dotcacc
 */
extern_c struct idx* C_idx_d3dotcacc(struct idx* L1_m,real L1_f,struct idx* L1_q)
{
TRACE_PUSH("C_idx_d3dotcacc");
{
struct idx* L_Tmp0;
{
RTERR_LOOPDIM((L1_q)->dim[0] != (L1_m)->dim[0]);
Midx_begin_bloop2(L2_lm, L1_m,L2_lq, L1_q,real) {
{
RTERR_LOOPDIM((&L2_lq)->dim[0] != (&L2_lm)->dim[0]);
Midx_begin_bloop2(L3_llm, &L2_lm,L3_llq, &L2_lq,real) {
C_idx_d1dotcacc(&L3_llm, L1_f, &L3_llq);
} Midx_end_bloop2(L3_llm, &L2_lm,L3_llq, &L2_lq,real);
}
} Midx_end_bloop2(L2_lm, L1_m,L2_lq, L1_q,real);
L_Tmp0 = L1_q;
}
TRACE_POP("C_idx_d3dotcacc");
return L_Tmp0;
}
}

/*
 * FUNCTION idx-d1addc
 */
extern_c char C_idx_d1addc(struct idx* L1_m,real L1_c,struct idx* L1_o)
{
TRACE_PUSH("C_idx_d1addc");
{
Msame_size1(L1_m,L1_o); 
{ register double *mp;
  register double *op;
  register int i, jmax = (L1_m)->dim[0];
  register int imat1_m0 = (L1_m)->mod[0];
  register int imat2_m0 = (L1_o)->mod[0];
  mp = IDX_PTR((L1_m),double);
  op = IDX_PTR((L1_o),double);
  for (i=0; i <jmax; i++){;
*op = *mp + (L1_c);
    mp += imat1_m0;
    op += imat2_m0;
  } }
TRACE_POP("C_idx_d1addc");
return 0;
}
}

/*
 * FUNCTION idx-d2addc
 */
extern_c struct idx* C_idx_d2addc(struct idx* L1_m,real L1_f,struct idx* L1_q)
{
TRACE_PUSH("C_idx_d2addc");
{
struct idx* L_Tmp0;
{
RTERR_LOOPDIM((L1_q)->dim[0] != (L1_m)->dim[0]);
Midx_begin_bloop2(L2_lm, L1_m,L2_lq, L1_q,real) {
C_idx_d1addc(&L2_lm, L1_f, &L2_lq);
} Midx_end_bloop2(L2_lm, L1_m,L2_lq, L1_q,real);
L_Tmp0 = L1_q;
}
TRACE_POP("C_idx_d2addc");
return L_Tmp0;
}
}

/*
 * FUNCTION idx-d3addc
 */
extern_c struct idx* C_idx_d3addc(struct idx* L1_m,real L1_f,struct idx* L1_q)
{
TRACE_PUSH("C_idx_d3addc");
{
struct idx* L_Tmp0;
{
RTERR_LOOPDIM((L1_q)->dim[0] != (L1_m)->dim[0]);
Midx_begin_bloop2(L2_lm, L1_m,L2_lq, L1_q,real) {
{
RTERR_LOOPDIM((&L2_lq)->dim[0] != (&L2_lm)->dim[0]);
Midx_begin_bloop2(L3_llm, &L2_lm,L3_llq, &L2_lq,real) {
C_idx_d1addc(&L3_llm, L1_f, &L3_llq);
} Midx_end_bloop2(L3_llm, &L2_lm,L3_llq, &L2_lq,real);
}
} Midx_end_bloop2(L2_lm, L1_m,L2_lq, L1_q,real);
L_Tmp0 = L1_q;
}
TRACE_POP("C_idx_d3addc");
return L_Tmp0;
}
}

/*
 * FUNCTION idx-d1lincomb
 */
extern_c char C_idx_d1lincomb(struct idx* L1_x,real L1_cx,struct idx* L1_y,real L1_cy,struct idx* L1_z)
{
TRACE_PUSH("C_idx_d1lincomb");
{
Msame_size1(L1_x,L1_y); 
Msame_size1(L1_x,L1_z); 
{ register double *xp;
  register double *yp;
  register double *zp;
  register int i, jmax = (L1_x)->dim[0];
  register int imat1_m0 = (L1_x)->mod[0];
  register int imat2_m0 = (L1_y)->mod[0];
  register int imat3_m0 = (L1_z)->mod[0];
  xp = IDX_PTR((L1_x),double);
  yp = IDX_PTR((L1_y),double);
  zp = IDX_PTR((L1_z),double);
  for (i=0; i <jmax; i++){;
*zp = L1_cx*(*xp) + L1_cy*(*yp);
    xp += imat1_m0;
    yp += imat2_m0;
    zp += imat3_m0;
  } }
TRACE_POP("C_idx_d1lincomb");
return 0;
}
}

/*
 * FUNCTION idx-d1tanh
 */
extern_c char C_idx_d1tanh(struct idx* L1_x,struct idx* L1_y)
{
TRACE_PUSH("C_idx_d1tanh");
{
Msame_size1(L1_x,L1_y); 
{ register double *xp;
  register double *yp;
  register int i, jmax = (L1_x)->dim[0];
  register int imat1_m0 = (L1_x)->mod[0];
  register int imat2_m0 = (L1_y)->mod[0];
  xp = IDX_PTR((L1_x),double);
  yp = IDX_PTR((L1_y),double);
  for (i=0; i <jmax; i++){;
*yp = Dtanh(*xp);
    xp += imat1_m0;
    yp += imat2_m0;
  } }
TRACE_POP("C_idx_d1tanh");
return 0;
}
}

/*
 * FUNCTION idx-d1inv
 */
extern_c char C_idx_d1inv(struct idx* L1_x,struct idx* L1_y)
{
TRACE_PUSH("C_idx_d1inv");
{
Msame_size1(L1_x,L1_y); 
{ register double *xp;
  register double *yp;
  register int i, jmax = (L1_x)->dim[0];
  register int imat1_m0 = (L1_x)->mod[0];
  register int imat2_m0 = (L1_y)->mod[0];
  xp = IDX_PTR((L1_x),double);
  yp = IDX_PTR((L1_y),double);
  for (i=0; i <jmax; i++){;
*yp = 1.0/(*xp);
    xp += imat1_m0;
    yp += imat2_m0;
  } }
TRACE_POP("C_idx_d1inv");
return 0;
}
}

/*
 * FUNCTION idx-d1sign
 */
extern_c char C_idx_d1sign(struct idx* L1_m,struct idx* L1_o)
{
TRACE_PUSH("C_idx_d1sign");
{
Msame_size1(L1_m,L1_o); 
{ register double *mp;
  register double *op;
  register int i, jmax = (L1_m)->dim[0];
  register int imat1_m0 = (L1_m)->mod[0];
  register int imat2_m0 = (L1_o)->mod[0];
  mp = IDX_PTR((L1_m),double);
  op = IDX_PTR((L1_o),double);
  for (i=0; i <jmax; i++){;
*op = ((*mp>0) ? 1 : -1);
    mp += imat1_m0;
    op += imat2_m0;
  } }
TRACE_POP("C_idx_d1sign");
return 0;
}
}

/*
 * FUNCTION idx-d1clip
 */
extern_c char C_idx_d1clip(struct idx* L1_m,struct idx* L1_o)
{
TRACE_PUSH("C_idx_d1clip");
{
Msame_size1(L1_m,L1_o); 
{ register double *mp;
  register double *op;
  register int i, jmax = (L1_m)->dim[0];
  register int imat1_m0 = (L1_m)->mod[0];
  register int imat2_m0 = (L1_o)->mod[0];
  mp = IDX_PTR((L1_m),double);
  op = IDX_PTR((L1_o),double);
  for (i=0; i <jmax; i++){;
*op = ((*mp>0) ? *mp : 0);
    mp += imat1_m0;
    op += imat2_m0;
  } }
TRACE_POP("C_idx_d1clip");
return 0;
}
}

/*
 * FUNCTION idx-d1sup
 */
extern_c real C_idx_d1sup(struct idx* L1_m)
{
TRACE_PUSH("C_idx_d1sup");
{
real L_Tmp0;
{
real L2_1_v;
RTERR_BOUND(0>=(L1_m)->dim[0]);
L2_1_v = IDX_PTR(L1_m,real)[(L1_m)->mod[0]*((int)0)];
{ register double *mp;
  register int i, jmax = (L1_m)->dim[0];
  register int imat1_m0 = (L1_m)->mod[0];
  mp = IDX_PTR((L1_m),double);
  for (i=0; i <jmax; i++){;
if ((*mp)>(L2_1_v)) { L2_1_v = *mp; }
    mp += imat1_m0;
  } }
L_Tmp0 = L2_1_v;
}
TRACE_POP("C_idx_d1sup");
return L_Tmp0;
}
}

/*
 * FUNCTION idx-d1inf
 */
extern_c real C_idx_d1inf(struct idx* L1_m)
{
TRACE_PUSH("C_idx_d1inf");
{
real L_Tmp0;
{
real L2_1_v;
RTERR_BOUND(0>=(L1_m)->dim[0]);
L2_1_v = IDX_PTR(L1_m,real)[(L1_m)->mod[0]*((int)0)];
{ register double *mp;
  register int i, jmax = (L1_m)->dim[0];
  register int imat1_m0 = (L1_m)->mod[0];
  mp = IDX_PTR((L1_m),double);
  for (i=0; i <jmax; i++){;
if ((*mp)<(L2_1_v)) { L2_1_v = *mp; }
    mp += imat1_m0;
  } }
L_Tmp0 = L2_1_v;
}
TRACE_POP("C_idx_d1inf");
return L_Tmp0;
}
}

/*
 * FUNCTION idx-d1indexmax
 */
extern_c intg C_idx_d1indexmax(struct idx* L1_m)
{
TRACE_PUSH("C_idx_d1indexmax");
{
intg L_Tmp0;
{
intg L2_1_n;
real L2_2_v;
L2_1_n = 0;
RTERR_BOUND(0>=(L1_m)->dim[0]);
L2_2_v = IDX_PTR(L1_m,real)[(L1_m)->mod[0]*((int)0)];
{ register double *mp;
  register int i, jmax = (L1_m)->dim[0];
  register int imat1_m0 = (L1_m)->mod[0];
  mp = IDX_PTR((L1_m),double);
  for (i=0; i <jmax; i++){;
if ((*mp)>(L2_2_v)) { L2_2_v = *mp; L2_1_n = i; }
    mp += imat1_m0;
  } }
L_Tmp0 = L2_1_n;
}
TRACE_POP("C_idx_d1indexmax");
return L_Tmp0;
}
}

/*
 * FUNCTION idx-d1indexmin
 */
extern_c intg C_idx_d1indexmin(struct idx* L1_m)
{
TRACE_PUSH("C_idx_d1indexmin");
{
intg L_Tmp0;
{
intg L2_1_n;
real L2_2_v;
L2_1_n = 0;
RTERR_BOUND(0>=(L1_m)->dim[0]);
L2_2_v = IDX_PTR(L1_m,real)[(L1_m)->mod[0]*((int)0)];
{ register double *mp;
  register int i, jmax = (L1_m)->dim[0];
  register int imat1_m0 = (L1_m)->mod[0];
  mp = IDX_PTR((L1_m),double);
  for (i=0; i <jmax; i++){;
if ((*mp)<(L2_2_v)) { L2_2_v = *mp; L2_1_n = i; }
    mp += imat1_m0;
  } }
L_Tmp0 = L2_1_n;
}
TRACE_POP("C_idx_d1indexmin");
return L_Tmp0;
}
}

/*
 * FUNCTION idx-d1fill-with-index
 */
extern_c char C_idx_d1fill_with_index(struct idx* L1_m)
{
TRACE_PUSH("C_idx_d1fill_with_index");
{
{ register double *mp;
  register int i, jmax = (L1_m)->dim[0];
  register int imat1_m0 = (L1_m)->mod[0];
  mp = IDX_PTR((L1_m),double);
  for (i=0; i <jmax; i++){;
*mp = (double)i;
    mp += imat1_m0;
  } }
TRACE_POP("C_idx_d1fill_with_index");
return 0;
}
}

/*
 * FUNCTION idx-d1avg
 */
extern_c real C_idx_d1avg(struct idx* L1_m)
{
TRACE_PUSH("C_idx_d1avg");
{
real L_Tmp0;
{
real L2_1_v;
real L2_2_n;
L2_1_v = 0;
L2_2_n = (L1_m)->dim[0];
{ register double *mp;
  register int i, jmax = (L1_m)->dim[0];
  register int imat1_m0 = (L1_m)->mod[0];
  mp = IDX_PTR((L1_m),double);
  for (i=0; i <jmax; i++){;
L2_1_v += (*mp);
    mp += imat1_m0;
  } }
L_Tmp0 = (L2_1_v/(real)L2_2_n);
}
TRACE_POP("C_idx_d1avg");
return L_Tmp0;
}
}

/*
 * FUNCTION idx-d1prod
 */
extern_c real C_idx_d1prod(struct idx* L1_m)
{
TRACE_PUSH("C_idx_d1prod");
{
real L_Tmp0;
{
real L2_1_v;
L2_1_v = 1;
{ register double *mp;
  register int i, jmax = (L1_m)->dim[0];
  register int imat1_m0 = (L1_m)->mod[0];
  mp = IDX_PTR((L1_m),double);
  for (i=0; i <jmax; i++){;
L2_1_v = L2_1_v*(*mp);
    mp += imat1_m0;
  } }
L_Tmp0 = L2_1_v;
}
TRACE_POP("C_idx_d1prod");
return L_Tmp0;
}
}

/*
 * FUNCTION idx-d1logsum
 */
extern_c real C_idx_d1logsum(struct idx* L1_m)
{
TRACE_PUSH("C_idx_d1logsum");
{
real L_Tmp0;
{
real L2_1_exp_offset;
real L2_2_n;
real L2_3_r;
RTERR_BOUND(0>=(L1_m)->dim[0]);
L2_1_exp_offset = IDX_PTR(L1_m,real)[(L1_m)->mod[0]*((int)0)];
L2_2_n = (L1_m)->dim[0];
L2_3_r = 0;
{ register double *mp;
  register int i, jmax = (L1_m)->dim[0];
  register int imat1_m0 = (L1_m)->mod[0];
  mp = IDX_PTR((L1_m),double);
  for (i=0; i <jmax; i++){;
if ((*mp)<(L2_1_exp_offset)) { L2_1_exp_offset = *mp; }
    mp += imat1_m0;
  } }
{ register double *mp;
  register int i, jmax = (L1_m)->dim[0];
  register int imat1_m0 = (L1_m)->mod[0];
  mp = IDX_PTR((L1_m),double);
  for (i=0; i <jmax; i++){;
L2_3_r += Dexp( L2_1_exp_offset - *mp);
    mp += imat1_m0;
  } }
L_Tmp0 = (L2_1_exp_offset-Dlog((L2_3_r/(real)L2_2_n)));
}
TRACE_POP("C_idx_d1logsum");
return L_Tmp0;
}
}

/*
 * FUNCTION idx-d2logsum
 */
extern_c real C_idx_d2logsum(struct idx* L1_m)
{
TRACE_PUSH("C_idx_d2logsum");
{
real L_Tmp0;
{
real L2_1_exp_offset;
real L2_2_n;
real L2_3_r;
RTERR_BOUND(0>=(L1_m)->dim[0]);
RTERR_BOUND(0>=(L1_m)->dim[1]);
L2_1_exp_offset = IDX_PTR(L1_m,real)[(L1_m)->mod[0]*((int)0)+(L1_m)->mod[1]*((int)0)];
L2_2_n = ((L1_m)->dim[1]*(L1_m)->dim[0]);
L2_3_r = 0;
{
Midx_begin_bloop1(L3_m, L1_m,real) {
{ register double *mp;
  register int i, jmax = (&L3_m)->dim[0];
  register int imat1_m0 = (&L3_m)->mod[0];
  mp = IDX_PTR((&L3_m),double);
  for (i=0; i <jmax; i++){;
if ((*mp)<(L2_1_exp_offset)) { L2_1_exp_offset = *mp; }
    mp += imat1_m0;
  } }
} Midx_end_bloop1(L3_m, L1_m,real);
}
{
Midx_begin_bloop1(L3_m, L1_m,real) {
{ register double *mp;
  register int i, jmax = (&L3_m)->dim[0];
  register int imat1_m0 = (&L3_m)->mod[0];
  mp = IDX_PTR((&L3_m),double);
  for (i=0; i <jmax; i++){;
L2_3_r += Dexp( L2_1_exp_offset - *mp);
    mp += imat1_m0;
  } }
} Midx_end_bloop1(L3_m, L1_m,real);
}
L_Tmp0 = (L2_1_exp_offset-Dlog((L2_3_r/(real)L2_2_n)));
}
TRACE_POP("C_idx_d2logsum");
return L_Tmp0;
}
}

/*
 * FUNCTION idx-d1logadd
 */
extern_c real C_idx_d1logadd(struct idx* L1_m)
{
TRACE_PUSH("C_idx_d1logadd");
{
real L_Tmp0;
{
real L2_1_exp_offset;
real L2_2_r;
RTERR_BOUND(0>=(L1_m)->dim[0]);
L2_1_exp_offset = IDX_PTR(L1_m,real)[(L1_m)->mod[0]*((int)0)];
L2_2_r = 0;
{ register double *mp;
  register int i, jmax = (L1_m)->dim[0];
  register int imat1_m0 = (L1_m)->mod[0];
  mp = IDX_PTR((L1_m),double);
  for (i=0; i <jmax; i++){;
if ((*mp)<(L2_1_exp_offset)) { L2_1_exp_offset = *mp; }
    mp += imat1_m0;
  } }
{ register double *mp;
  register int i, jmax = (L1_m)->dim[0];
  register int imat1_m0 = (L1_m)->mod[0];
  mp = IDX_PTR((L1_m),double);
  for (i=0; i <jmax; i++){;
L2_2_r += Dexp( L2_1_exp_offset - *mp);
    mp += imat1_m0;
  } }
L_Tmp0 = (L2_1_exp_offset-Dlog(L2_2_r));
}
TRACE_POP("C_idx_d1logadd");
return L_Tmp0;
}
}

/*
 * FUNCTION idx-d2logadd
 */
extern_c real C_idx_d2logadd(struct idx* L1_m)
{
TRACE_PUSH("C_idx_d2logadd");
{
real L_Tmp0;
{
real L2_1_exp_offset;
real L2_2_r;
RTERR_BOUND(0>=(L1_m)->dim[0]);
RTERR_BOUND(0>=(L1_m)->dim[1]);
L2_1_exp_offset = IDX_PTR(L1_m,real)[(L1_m)->mod[0]*((int)0)+(L1_m)->mod[1]*((int)0)];
L2_2_r = 0;
{
Midx_begin_bloop1(L3_m, L1_m,real) {
{ register double *mp;
  register int i, jmax = (&L3_m)->dim[0];
  register int imat1_m0 = (&L3_m)->mod[0];
  mp = IDX_PTR((&L3_m),double);
  for (i=0; i <jmax; i++){;
if ((*mp)<(L2_1_exp_offset)) { L2_1_exp_offset = *mp; }
    mp += imat1_m0;
  } }
} Midx_end_bloop1(L3_m, L1_m,real);
}
{
Midx_begin_bloop1(L3_m, L1_m,real) {
{ register double *mp;
  register int i, jmax = (&L3_m)->dim[0];
  register int imat1_m0 = (&L3_m)->mod[0];
  mp = IDX_PTR((&L3_m),double);
  for (i=0; i <jmax; i++){;
L2_2_r += Dexp( L2_1_exp_offset - *mp);
    mp += imat1_m0;
  } }
} Midx_end_bloop1(L3_m, L1_m,real);
}
L_Tmp0 = (L2_1_exp_offset-Dlog(L2_2_r));
}
TRACE_POP("C_idx_d2logadd");
return L_Tmp0;
}
}

/*
 * FUNCTION idx-d1logaddb
 */
extern_c real C_idx_d1logaddb(struct idx* L1_m,real L1_beta)
{
TRACE_PUSH("C_idx_d1logaddb");
{
real L_Tmp0;
{
real L2_1_exp_offset;
real L2_2_r;
RTERR_BOUND(0>=(L1_m)->dim[0]);
L2_1_exp_offset = IDX_PTR(L1_m,real)[(L1_m)->mod[0]*((int)0)];
L2_2_r = 0;
{ register double *mp;
  register int i, jmax = (L1_m)->dim[0];
  register int imat1_m0 = (L1_m)->mod[0];
  mp = IDX_PTR((L1_m),double);
  for (i=0; i <jmax; i++){;
if ((*mp)<(L2_1_exp_offset)) { L2_1_exp_offset = *mp; }
    mp += imat1_m0;
  } }
{ register double *mp;
  register int i, jmax = (L1_m)->dim[0];
  register int imat1_m0 = (L1_m)->mod[0];
  mp = IDX_PTR((L1_m),double);
  for (i=0; i <jmax; i++){;
L2_2_r += Dexp( L1_beta*(L2_1_exp_offset - *mp));
    mp += imat1_m0;
  } }
L_Tmp0 = (L2_1_exp_offset-(Dlog(L2_2_r)/(real)L1_beta));
}
TRACE_POP("C_idx_d1logaddb");
return L_Tmp0;
}
}

/*
 * FUNCTION idx-d2logaddb
 */
extern_c real C_idx_d2logaddb(struct idx* L1_m,real L1_beta)
{
TRACE_PUSH("C_idx_d2logaddb");
{
real L_Tmp0;
{
real L2_1_exp_offset;
real L2_2_r;
RTERR_BOUND(0>=(L1_m)->dim[0]);
RTERR_BOUND(0>=(L1_m)->dim[1]);
L2_1_exp_offset = IDX_PTR(L1_m,real)[(L1_m)->mod[0]*((int)0)+(L1_m)->mod[1]*((int)0)];
L2_2_r = 0;
{
Midx_begin_bloop1(L3_m, L1_m,real) {
{ register double *mp;
  register int i, jmax = (&L3_m)->dim[0];
  register int imat1_m0 = (&L3_m)->mod[0];
  mp = IDX_PTR((&L3_m),double);
  for (i=0; i <jmax; i++){;
if ((*mp)<(L2_1_exp_offset)) { L2_1_exp_offset = *mp; }
    mp += imat1_m0;
  } }
} Midx_end_bloop1(L3_m, L1_m,real);
}
{
Midx_begin_bloop1(L3_m, L1_m,real) {
{ register double *mp;
  register int i, jmax = (&L3_m)->dim[0];
  register int imat1_m0 = (&L3_m)->mod[0];
  mp = IDX_PTR((&L3_m),double);
  for (i=0; i <jmax; i++){;
L2_2_r += Dexp( L1_beta*(L2_1_exp_offset - *mp) );
    mp += imat1_m0;
  } }
} Midx_end_bloop1(L3_m, L1_m,real);
}
L_Tmp0 = (L2_1_exp_offset-(Dlog(L2_2_r)/(real)L1_beta));
}
TRACE_POP("C_idx_d2logaddb");
return L_Tmp0;
}
}

/*
 * FUNCTION idx-d1logdotd1
 */
extern_c real C_idx_d1logdotd1(struct idx* L1_m,struct idx* L1_p)
{
TRACE_PUSH("C_idx_d1logdotd1");
{
real L_Tmp0;
{
real L2_1_exp_offset;
real L2_2_r;
RTERR_BOUND(0>=(L1_m)->dim[0]);
L2_1_exp_offset = IDX_PTR(L1_m,real)[(L1_m)->mod[0]*((int)0)];
L2_2_r = 0;
{ register double *mp;
  register int i, jmax = (L1_m)->dim[0];
  register int imat1_m0 = (L1_m)->mod[0];
  mp = IDX_PTR((L1_m),double);
  for (i=0; i <jmax; i++){;
if ((*mp)<(L2_1_exp_offset)) { L2_1_exp_offset = *mp; }
    mp += imat1_m0;
  } }
{ register double *mp;
  register double *pp;
  register int i, jmax = (L1_m)->dim[0];
  register int imat1_m0 = (L1_m)->mod[0];
  register int imat2_m0 = (L1_p)->mod[0];
  mp = IDX_PTR((L1_m),double);
  pp = IDX_PTR((L1_p),double);
  for (i=0; i <jmax; i++){;
L2_2_r += *pp * Dexp( L2_1_exp_offset - *mp);
    mp += imat1_m0;
    pp += imat2_m0;
  } }
L_Tmp0 = (L2_1_exp_offset-Dlog(L2_2_r));
}
TRACE_POP("C_idx_d1logdotd1");
return L_Tmp0;
}
}

/*
 * FUNCTION idx-d1blogdotd1
 */
extern_c char C_idx_d1blogdotd1(struct idx* L1_m,struct idx* L1_p,struct idx* L1_out)
{
TRACE_PUSH("C_idx_d1blogdotd1");
{
char L_Tmp0;
{
real L2_1_exp_offset;
real L2_2_r;
RTERR_BOUND(0>=(L1_m)->dim[0]);
L2_1_exp_offset = IDX_PTR(L1_m,real)[(L1_m)->mod[0]*((int)0)];
L2_2_r = 0;
{ register double *mp;
  register int i, jmax = (L1_m)->dim[0];
  register int imat1_m0 = (L1_m)->mod[0];
  mp = IDX_PTR((L1_m),double);
  for (i=0; i <jmax; i++){;
if ((*mp)<(L2_1_exp_offset)) { L2_1_exp_offset = *mp; }
    mp += imat1_m0;
  } }
{ register double *mp;
  register double *pp;
  register double *op;
  register int i, jmax = (L1_m)->dim[0];
  register int imat1_m0 = (L1_m)->mod[0];
  register int imat2_m0 = (L1_p)->mod[0];
  register int imat3_m0 = (L1_out)->mod[0];
  mp = IDX_PTR((L1_m),double);
  pp = IDX_PTR((L1_p),double);
  op = IDX_PTR((L1_out),double);
  for (i=0; i <jmax; i++){;
*op = *pp * Dexp( L2_1_exp_offset - *mp);
    mp += imat1_m0;
    pp += imat2_m0;
    op += imat3_m0;
  } }
{
real L3_3_sum_exp;
L3_3_sum_exp = 0;
{ register double *op;
  register int i, jmax = (L1_out)->dim[0];
  register int imat1_m0 = (L1_out)->mod[0];
  op = IDX_PTR((L1_out),double);
  for (i=0; i <jmax; i++){;
L3_3_sum_exp += *op;
    op += imat1_m0;
  } }
L3_3_sum_exp = (1/(real)L3_3_sum_exp);
{ register double *op;
  register int i, jmax = (L1_out)->dim[0];
  register int imat1_m0 = (L1_out)->mod[0];
  op = IDX_PTR((L1_out),double);
  for (i=0; i <jmax; i++){;
*op = *op * L3_3_sum_exp;
    op += imat1_m0;
  } }
L_Tmp0 = 0;
}
}
TRACE_POP("C_idx_d1blogdotd1");
return 0;
}
}

/*
 * FUNCTION idx-d2logdotd2
 */
extern_c real C_idx_d2logdotd2(struct idx* L1_m,struct idx* L1_p)
{
TRACE_PUSH("C_idx_d2logdotd2");
{
real L_Tmp0;
{
real L2_1_exp_offset;
real L2_2_r;
RTERR_BOUND(0>=(L1_m)->dim[0]);
RTERR_BOUND(0>=(L1_m)->dim[1]);
L2_1_exp_offset = IDX_PTR(L1_m,real)[(L1_m)->mod[0]*((int)0)+(L1_m)->mod[1]*((int)0)];
L2_2_r = 0;
{
Midx_begin_bloop1(L3_m, L1_m,real) {
{ register double *mp;
  register int i, jmax = (&L3_m)->dim[0];
  register int imat1_m0 = (&L3_m)->mod[0];
  mp = IDX_PTR((&L3_m),double);
  for (i=0; i <jmax; i++){;
if ((*mp)<(L2_1_exp_offset)) { L2_1_exp_offset = *mp; }
    mp += imat1_m0;
  } }
} Midx_end_bloop1(L3_m, L1_m,real);
}
{
RTERR_LOOPDIM((L1_p)->dim[0] != (L1_m)->dim[0]);
Midx_begin_bloop2(L3_m, L1_m,L3_p, L1_p,real) {
{ register double *mp;
  register double *pp;
  register int i, jmax = (&L3_m)->dim[0];
  register int imat1_m0 = (&L3_m)->mod[0];
  register int imat2_m0 = (&L3_p)->mod[0];
  mp = IDX_PTR((&L3_m),double);
  pp = IDX_PTR((&L3_p),double);
  for (i=0; i <jmax; i++){;
L2_2_r += *pp * Dexp( L2_1_exp_offset - *mp);
    mp += imat1_m0;
    pp += imat2_m0;
  } }
} Midx_end_bloop2(L3_m, L1_m,L3_p, L1_p,real);
}
L_Tmp0 = (L2_1_exp_offset-Dlog(L2_2_r));
}
TRACE_POP("C_idx_d2logdotd2");
return L_Tmp0;
}
}

/*
 * FUNCTION idx-d1subextd1
 */
extern_c char C_idx_d1subextd1(struct idx* L1_x,struct idx* L1_y,struct idx* L1_z)
{
TRACE_PUSH("C_idx_d1subextd1");
{
{
RTERR_LOOPDIM((L1_z)->dim[0] != (L1_x)->dim[0]);
Midx_begin_bloop2(L2_xi, L1_x,L2_zi, L1_z,real) {
{
real L3_0_x;
L3_0_x =  *IDX_PTR(&L2_xi,real);
{ register double *yi;
  register double *zij;
  register int i, jmax = (L1_y)->dim[0];
  register int imat1_m0 = (L1_y)->mod[0];
  register int imat2_m0 = (&L2_zi)->mod[0];
  yi = IDX_PTR((L1_y),double);
  zij = IDX_PTR((&L2_zi),double);
  for (i=0; i <jmax; i++){;
*zij = L3_0_x - *yi;
    yi += imat1_m0;
    zij += imat2_m0;
  } }
}
} Midx_end_bloop2(L2_xi, L1_x,L2_zi, L1_z,real);
}
TRACE_POP("C_idx_d1subextd1");
return 0;
}
}

/*
 * FUNCTION idx-d1subd0
 */
extern_c char C_idx_d1subd0(struct idx* L1_m,struct idx* L1_y,struct idx* L1_o)
{
TRACE_PUSH("C_idx_d1subd0");
{
{
real L2_0_v;
L2_0_v =  *IDX_PTR(L1_y,real);
Msame_size1(L1_m,L1_o); 
{ register double *mp;
  register double *op;
  register int i, jmax = (L1_m)->dim[0];
  register int imat1_m0 = (L1_m)->mod[0];
  register int imat2_m0 = (L1_o)->mod[0];
  mp = IDX_PTR((L1_m),double);
  op = IDX_PTR((L1_o),double);
  for (i=0; i <jmax; i++){;
*op = *mp - L2_0_v;
    mp += imat1_m0;
    op += imat2_m0;
  } }
}
TRACE_POP("C_idx_d1subd0");
return 0;
}
}

/*
 * FUNCTION idx-d1mulacc
 */
extern_c struct idx* C_idx_d1mulacc(struct idx* L1_x,struct idx* L1_y,struct idx* L1_z)
{
TRACE_PUSH("C_idx_d1mulacc");
{
struct idx* L_Tmp0;
{
RTERR_LOOPDIM((L1_z)->dim[0] != (L1_y)->dim[0] || (L1_z)->dim[0] != (L1_x)->dim[0]);
Midx_begin_bloop3(L2_xi, L1_x,L2_yi, L1_y,L2_zi, L1_z,real) {
*IDX_PTR(&L2_zi,real) = ( *IDX_PTR(&L2_zi,real)+( *IDX_PTR(&L2_xi,real)* *IDX_PTR(&L2_yi,real)));
} Midx_end_bloop3(L2_xi, L1_x,L2_yi, L1_y,L2_zi, L1_z,real);
L_Tmp0 = L1_z;
}
TRACE_POP("C_idx_d1mulacc");
return L_Tmp0;
}
}

/*
 * FUNCTION idx-d1entropy
 */
extern_c real C_idx_d1entropy(struct idx* L1_m,real L1_c)
{
TRACE_PUSH("C_idx_d1entropy");
{
real L_Tmp0;
{
real L2_1_s;
real L2_2_r;
L2_1_s = 0;
L2_2_r = 0;
{ register double *p;
  register int i, jmax = (L1_m)->dim[0];
  register int imat1_m0 = (L1_m)->mod[0];
  p = IDX_PTR((L1_m),double);
  for (i=0; i <jmax; i++){;
 
        (L2_1_s) += *p;
    p += imat1_m0;
  } }
L2_1_s = (1/(real)L2_1_s);
{ register double *p;
  register int i, jmax = (L1_m)->dim[0];
  register int imat1_m0 = (L1_m)->mod[0];
  p = IDX_PTR((L1_m),double);
  for (i=0; i <jmax; i++){;
{
        double z;
        z = ((double)((*p) + (L1_c))) * (L2_1_s);
        (L2_2_r) += z * log(z);
        }
    p += imat1_m0;
  } }
L_Tmp0 = (-L2_2_r);
}
TRACE_POP("C_idx_d1entropy");
return L_Tmp0;
}
}

/*
 * FUNCTION idx-d1subsample-fast
 */
extern_c struct idx* C_idx_d1subsample_fast(struct idx* L1_in,intg L1_nlin,struct idx* L2_1_matrix,struct srg* L2_1_srg)
{
TRACE_PUSH("C_idx_d1subsample_fast");
{
struct idx* L_Tmp0;
{
real L2_1_h;
real L2_2_nh;
Midx_declare(L3_3_0_clone, 1);
struct idx* L2_4_inp;
struct idx* L2_5_out;
Midx_init(L3_3_0_clone, 1);
L2_1_h = (L1_in)->dim[0];
L2_2_nh = (L2_1_h/(real)L1_nlin);
L2_2_nh = ((intg)floor((double)L2_2_nh));
{
struct idx* L3_6___m;
real L_Tmp7;
Midx_clone1(L3_3_0_clone, L1_in);
L3_6___m = L3_3_0_clone;
L_Tmp7 = (L1_nlin*L2_2_nh);
RTERR_GEN((((intg)L_Tmp7)<1 || ((intg)0)<0), "illegal 'size' or 'offset'");
RTERR_GEN((((intg)0)+((intg)L_Tmp7) > (L3_6___m)->dim[((intg)0)]), "specified interval is too large");
Midx_narrow(L3_6___m,((intg)0),((intg)L_Tmp7),((intg)0),real);
L2_4_inp = L3_6___m;
}
(L2_1_matrix)->srg = L2_1_srg;
Midx_init_dim1(L2_1_matrix, L2_2_nh);
RTERR_DIM(L2_1_matrix->dim[0]<=0);
L2_5_out = L2_1_matrix;
{
      double *pin;
      double *pout;
      int i, imax = ((L2_5_out))->dim[0];
      int inp_mod = ((L2_4_inp))->mod[0];
      int out_mod = ((L2_5_out))->mod[0];
      double norm = 1.0/(double)((L1_nlin));
      register int k;
      pin = IDX_PTR (((L2_4_inp)), double);
      pout = IDX_PTR (((L2_5_out)), double);
      for (i = 0; i < imax; i++) {
        register double acc0 = 0;
        for (k=0; k<(L1_nlin); k++) {
             acc0 += *pin;
             pin += inp_mod;
             }
        *pout = acc0*norm;
        pout += out_mod;
      }}
L_Tmp0 = L2_5_out;
}
TRACE_POP("C_idx_d1subsample_fast");
return L_Tmp0;
}
}

/*
 * FUNCTION idx-d3dotd3
 */
extern_c real C_idx_d3dotd3(struct idx* L1_a,struct idx* L1_b,struct idx* L1_c)
{
TRACE_PUSH("C_idx_d3dotd3");
{
real L_Tmp0;
{
real L2_1_r;
L2_1_r = 0;
{
RTERR_LOOPDIM((L1_b)->dim[0] != (L1_a)->dim[0]);
Midx_begin_bloop2(L3_ai, L1_a,L3_bi, L1_b,real) {
{
RTERR_LOOPDIM((&L3_bi)->dim[0] != (&L3_ai)->dim[0]);
Midx_begin_bloop2(L4_aij, &L3_ai,L4_bij, &L3_bi,real) {
{
RTERR_LOOPDIM((&L4_bij)->dim[0] != (&L4_aij)->dim[0]);
Midx_begin_bloop2(L5_aijk, &L4_aij,L5_bijk, &L4_bij,real) {
L2_1_r = (L2_1_r+( *IDX_PTR(&L5_aijk,real)* *IDX_PTR(&L5_bijk,real)));
} Midx_end_bloop2(L5_aijk, &L4_aij,L5_bijk, &L4_bij,real);
}
} Midx_end_bloop2(L4_aij, &L3_ai,L4_bij, &L3_bi,real);
}
} Midx_end_bloop2(L3_ai, L1_a,L3_bi, L1_b,real);
}
*IDX_PTR(L1_c,real) = L2_1_r;
L_Tmp0 = L2_1_r;
}
TRACE_POP("C_idx_d3dotd3");
return L_Tmp0;
}
}

/*
 * FUNCTION idx-d3dotd2
 */
extern_c struct idx* C_idx_d3dotd2(struct idx* L1_x,struct idx* L1_y,struct idx* L1_z)
{
TRACE_PUSH("C_idx_d3dotd2");
{
struct idx* L_Tmp0;
{
RTERR_LOOPDIM((L1_x)->dim[0] != (L1_z)->dim[0]);
Midx_begin_bloop2(L2_z_i, L1_z,L2_x_i, L1_x,real) {
{
real L3_1_r;
L3_1_r = 0;
{
RTERR_LOOPDIM((&L2_x_i)->dim[0] != (L1_y)->dim[0]);
Midx_begin_bloop2(L4_y_j, L1_y,L4_x_ij, &L2_x_i,real) {
{
RTERR_LOOPDIM((&L4_x_ij)->dim[0] != (&L4_y_j)->dim[0]);
Midx_begin_bloop2(L5_y_jk, &L4_y_j,L5_x_ijk, &L4_x_ij,real) {
L3_1_r = (L3_1_r+( *IDX_PTR(&L5_y_jk,real)* *IDX_PTR(&L5_x_ijk,real)));
} Midx_end_bloop2(L5_y_jk, &L4_y_j,L5_x_ijk, &L4_x_ij,real);
}
} Midx_end_bloop2(L4_y_j, L1_y,L4_x_ij, &L2_x_i,real);
}
*IDX_PTR(&L2_z_i,real) = L3_1_r;
}
} Midx_end_bloop2(L2_z_i, L1_z,L2_x_i, L1_x,real);
L_Tmp0 = L1_x;
}
TRACE_POP("C_idx_d3dotd2");
return L_Tmp0;
}
}

/*
 * FUNCTION idx-d3dotd1
 */
extern_c struct idx* C_idx_d3dotd1(struct idx* L1_x,struct idx* L1_y,struct idx* L1_z)
{
TRACE_PUSH("C_idx_d3dotd1");
{
struct idx* L_Tmp0;
Midx_m2clear(L1_z,real);
{
RTERR_LOOPDIM((L1_x)->dim[0] != (L1_y)->dim[0]);
Midx_begin_bloop2(L2_y_i, L1_y,L2_x_i, L1_x,real) {
{
real L3_1_yi;
L3_1_yi =  *IDX_PTR(&L2_y_i,real);
{
RTERR_LOOPDIM((&L2_x_i)->dim[0] != (L1_z)->dim[0]);
Midx_begin_bloop2(L4_z_j, L1_z,L4_x_ij, &L2_x_i,real) {
{
RTERR_LOOPDIM((&L4_x_ij)->dim[0] != (&L4_z_j)->dim[0]);
Midx_begin_bloop2(L5_z_jk, &L4_z_j,L5_x_ijk, &L4_x_ij,real) {
*IDX_PTR(&L5_z_jk,real) = ( *IDX_PTR(&L5_z_jk,real)+(L3_1_yi* *IDX_PTR(&L5_x_ijk,real)));
} Midx_end_bloop2(L5_z_jk, &L4_z_j,L5_x_ijk, &L4_x_ij,real);
}
} Midx_end_bloop2(L4_z_j, L1_z,L4_x_ij, &L2_x_i,real);
}
}
} Midx_end_bloop2(L2_y_i, L1_y,L2_x_i, L1_x,real);
L_Tmp0 = L1_x;
}
TRACE_POP("C_idx_d3dotd1");
return L_Tmp0;
}
}

/*
 * FUNCTION idx-d3dotd1acc
 */
extern_c struct idx* C_idx_d3dotd1acc(struct idx* L1_x,struct idx* L1_y,struct idx* L1_z)
{
TRACE_PUSH("C_idx_d3dotd1acc");
{
struct idx* L_Tmp0;
{
RTERR_LOOPDIM((L1_x)->dim[0] != (L1_y)->dim[0]);
Midx_begin_bloop2(L2_y_i, L1_y,L2_x_i, L1_x,real) {
{
real L3_1_yi;
L3_1_yi =  *IDX_PTR(&L2_y_i,real);
{
RTERR_LOOPDIM((&L2_x_i)->dim[0] != (L1_z)->dim[0]);
Midx_begin_bloop2(L4_z_j, L1_z,L4_x_ij, &L2_x_i,real) {
{
RTERR_LOOPDIM((&L4_x_ij)->dim[0] != (&L4_z_j)->dim[0]);
Midx_begin_bloop2(L5_z_jk, &L4_z_j,L5_x_ijk, &L4_x_ij,real) {
*IDX_PTR(&L5_z_jk,real) = ( *IDX_PTR(&L5_z_jk,real)+(L3_1_yi* *IDX_PTR(&L5_x_ijk,real)));
} Midx_end_bloop2(L5_z_jk, &L4_z_j,L5_x_ijk, &L4_x_ij,real);
}
} Midx_end_bloop2(L4_z_j, L1_z,L4_x_ij, &L2_x_i,real);
}
}
} Midx_end_bloop2(L2_y_i, L1_y,L2_x_i, L1_x,real);
L_Tmp0 = L1_x;
}
TRACE_POP("C_idx_d3dotd1acc");
return L_Tmp0;
}
}

/*
 * FUNCTION idx-d3extd1
 */
extern_c struct idx* C_idx_d3extd1(struct idx* L1_x,struct idx* L1_y,struct idx* L1_z)
{
TRACE_PUSH("C_idx_d3extd1");
{
struct idx* L_Tmp0;
{
RTERR_LOOPDIM((L1_z)->dim[0] != (L1_x)->dim[0]);
Midx_begin_bloop2(L2_xi, L1_x,L2_zi, L1_z,real) {
{
RTERR_LOOPDIM((&L2_zi)->dim[0] != (&L2_xi)->dim[0]);
Midx_begin_bloop2(L3_xij, &L2_xi,L3_zij, &L2_zi,real) {
{
RTERR_LOOPDIM((&L3_zij)->dim[0] != (&L3_xij)->dim[0]);
Midx_begin_bloop2(L4_xijk, &L3_xij,L4_zijk, &L3_zij,real) {
{
RTERR_LOOPDIM((&L4_zijk)->dim[0] != (L1_y)->dim[0]);
Midx_begin_bloop2(L5_yl, L1_y,L5_zijkl, &L4_zijk,real) {
*IDX_PTR(&L5_zijkl,real) = ( *IDX_PTR(&L4_xijk,real)* *IDX_PTR(&L5_yl,real));
} Midx_end_bloop2(L5_yl, L1_y,L5_zijkl, &L4_zijk,real);
}
} Midx_end_bloop2(L4_xijk, &L3_xij,L4_zijk, &L3_zij,real);
}
} Midx_end_bloop2(L3_xij, &L2_xi,L3_zij, &L2_zi,real);
}
} Midx_end_bloop2(L2_xi, L1_x,L2_zi, L1_z,real);
L_Tmp0 = L1_z;
}
TRACE_POP("C_idx_d3extd1");
return L_Tmp0;
}
}

/*
 * FUNCTION idx-d1extd3
 */
extern_c struct idx* C_idx_d1extd3(struct idx* L1_x,struct idx* L1_y,struct idx* L1_z)
{
TRACE_PUSH("C_idx_d1extd3");
{
struct idx* L_Tmp0;
{
RTERR_LOOPDIM((L1_z)->dim[0] != (L1_x)->dim[0]);
Midx_begin_bloop2(L2_xi, L1_x,L2_zi, L1_z,real) {
{
real L3_1_x_i;
L3_1_x_i =  *IDX_PTR(&L2_xi,real);
{
RTERR_LOOPDIM((&L2_zi)->dim[0] != (L1_y)->dim[0]);
Midx_begin_bloop2(L4_yi, L1_y,L4_zij, &L2_zi,real) {
{
RTERR_LOOPDIM((&L4_zij)->dim[0] != (&L4_yi)->dim[0]);
Midx_begin_bloop2(L5_yij, &L4_yi,L5_zijk, &L4_zij,real) {
{
RTERR_LOOPDIM((&L5_zijk)->dim[0] != (&L5_yij)->dim[0]);
Midx_begin_bloop2(L6_yijk, &L5_yij,L6_zijkl, &L5_zijk,real) {
*IDX_PTR(&L6_zijkl,real) = (L3_1_x_i* *IDX_PTR(&L6_yijk,real));
} Midx_end_bloop2(L6_yijk, &L5_yij,L6_zijkl, &L5_zijk,real);
}
} Midx_end_bloop2(L5_yij, &L4_yi,L5_zijk, &L4_zij,real);
}
} Midx_end_bloop2(L4_yi, L1_y,L4_zij, &L2_zi,real);
}
}
} Midx_end_bloop2(L2_xi, L1_x,L2_zi, L1_z,real);
L_Tmp0 = L1_z;
}
TRACE_POP("C_idx_d1extd3");
return L_Tmp0;
}
}

/*
 * FUNCTION idx-d1extd2
 */
extern_c struct idx* C_idx_d1extd2(struct idx* L1_x,struct idx* L1_y,struct idx* L1_z)
{
TRACE_PUSH("C_idx_d1extd2");
{
struct idx* L_Tmp0;
{
RTERR_LOOPDIM((L1_z)->dim[0] != (L1_x)->dim[0]);
Midx_begin_bloop2(L2_xi, L1_x,L2_zi, L1_z,real) {
{
real L3_1_x_i;
L3_1_x_i =  *IDX_PTR(&L2_xi,real);
{
RTERR_LOOPDIM((&L2_zi)->dim[0] != (L1_y)->dim[0]);
Midx_begin_bloop2(L4_yj, L1_y,L4_zij, &L2_zi,real) {
{
RTERR_LOOPDIM((&L4_zij)->dim[0] != (&L4_yj)->dim[0]);
Midx_begin_bloop2(L5_yjk, &L4_yj,L5_zijk, &L4_zij,real) {
*IDX_PTR(&L5_zijk,real) = (L3_1_x_i* *IDX_PTR(&L5_yjk,real));
} Midx_end_bloop2(L5_yjk, &L4_yj,L5_zijk, &L4_zij,real);
}
} Midx_end_bloop2(L4_yj, L1_y,L4_zij, &L2_zi,real);
}
}
} Midx_end_bloop2(L2_xi, L1_x,L2_zi, L1_z,real);
L_Tmp0 = L1_z;
}
TRACE_POP("C_idx_d1extd2");
return L_Tmp0;
}
}

/*
 * FUNCTION idx-d4dotd1
 */
extern_c struct idx* C_idx_d4dotd1(struct idx* L1_x,struct idx* L1_y,struct idx* L1_z)
{
TRACE_PUSH("C_idx_d4dotd1");
{
struct idx* L_Tmp0;
{
Midx_begin_bloop1(L2_in, L1_z,real) {
Midx_m2clear(&L2_in,real);
} Midx_end_bloop1(L2_in, L1_z,real);
}
{
RTERR_LOOPDIM((L1_x)->dim[0] != (L1_y)->dim[0]);
Midx_begin_bloop2(L2_y_i, L1_y,L2_x_i, L1_x,real) {
{
real L3_1_yi;
L3_1_yi =  *IDX_PTR(&L2_y_i,real);
{
RTERR_LOOPDIM((&L2_x_i)->dim[0] != (L1_z)->dim[0]);
Midx_begin_bloop2(L4_z_j, L1_z,L4_x_ij, &L2_x_i,real) {
{
RTERR_LOOPDIM((&L4_x_ij)->dim[0] != (&L4_z_j)->dim[0]);
Midx_begin_bloop2(L5_z_jk, &L4_z_j,L5_x_ijk, &L4_x_ij,real) {
{
RTERR_LOOPDIM((&L5_x_ijk)->dim[0] != (&L5_z_jk)->dim[0]);
Midx_begin_bloop2(L6_z_jkl, &L5_z_jk,L6_x_ijkl, &L5_x_ijk,real) {
*IDX_PTR(&L6_z_jkl,real) = ( *IDX_PTR(&L6_z_jkl,real)+(L3_1_yi* *IDX_PTR(&L6_x_ijkl,real)));
} Midx_end_bloop2(L6_z_jkl, &L5_z_jk,L6_x_ijkl, &L5_x_ijk,real);
}
} Midx_end_bloop2(L5_z_jk, &L4_z_j,L5_x_ijk, &L4_x_ij,real);
}
} Midx_end_bloop2(L4_z_j, L1_z,L4_x_ij, &L2_x_i,real);
}
}
} Midx_end_bloop2(L2_y_i, L1_y,L2_x_i, L1_x,real);
L_Tmp0 = L1_x;
}
TRACE_POP("C_idx_d4dotd1");
return L_Tmp0;
}
}

/*
 * FUNCTION idx-d4dotd1acc
 */
extern_c struct idx* C_idx_d4dotd1acc(struct idx* L1_x,struct idx* L1_y,struct idx* L1_z)
{
TRACE_PUSH("C_idx_d4dotd1acc");
{
struct idx* L_Tmp0;
{
RTERR_LOOPDIM((L1_x)->dim[0] != (L1_y)->dim[0]);
Midx_begin_bloop2(L2_y_i, L1_y,L2_x_i, L1_x,real) {
{
real L3_1_yi;
L3_1_yi =  *IDX_PTR(&L2_y_i,real);
{
RTERR_LOOPDIM((&L2_x_i)->dim[0] != (L1_z)->dim[0]);
Midx_begin_bloop2(L4_z_j, L1_z,L4_x_ij, &L2_x_i,real) {
{
RTERR_LOOPDIM((&L4_x_ij)->dim[0] != (&L4_z_j)->dim[0]);
Midx_begin_bloop2(L5_z_jk, &L4_z_j,L5_x_ijk, &L4_x_ij,real) {
{
RTERR_LOOPDIM((&L5_x_ijk)->dim[0] != (&L5_z_jk)->dim[0]);
Midx_begin_bloop2(L6_z_jkl, &L5_z_jk,L6_x_ijkl, &L5_x_ijk,real) {
*IDX_PTR(&L6_z_jkl,real) = ( *IDX_PTR(&L6_z_jkl,real)+(L3_1_yi* *IDX_PTR(&L6_x_ijkl,real)));
} Midx_end_bloop2(L6_z_jkl, &L5_z_jk,L6_x_ijkl, &L5_x_ijk,real);
}
} Midx_end_bloop2(L5_z_jk, &L4_z_j,L5_x_ijk, &L4_x_ij,real);
}
} Midx_end_bloop2(L4_z_j, L1_z,L4_x_ij, &L2_x_i,real);
}
}
} Midx_end_bloop2(L2_y_i, L1_y,L2_x_i, L1_x,real);
L_Tmp0 = L1_x;
}
TRACE_POP("C_idx_d4dotd1acc");
return L_Tmp0;
}
}

/*
 * FUNCTION make-d2-place-target
 */
extern_c struct idx* C_make_d2_place_target(intg L1_n,struct idx* L2_0_matrix,struct srg* L2_0_srg)
{
TRACE_PUSH("C_make_d2_place_target");
{
struct idx* L_Tmp0;
{
struct idx* L2_1_m;
(L2_0_matrix)->srg = L2_0_srg;
Midx_init_dim2(L2_0_matrix, L1_n,L1_n);
RTERR_DIM(L2_0_matrix->dim[0]<=0);
RTERR_DIM(L2_0_matrix->dim[1]<=0);
Midx_maclear(L2_0_matrix, real);
L2_1_m = L2_0_matrix;
C_idx_d2fill(L2_1_m, -1);
{
real L3_2_i;
intg L_Tmp3;
L_Tmp3 = ((L1_n)-1);
L3_2_i = 0;
for(;
((1>0)?(L3_2_i<=L_Tmp3):(L3_2_i>=L_Tmp3));
(L3_2_i)+=1 ) {
RTERR_BOUND(L3_2_i<0 || L3_2_i>=(L2_1_m)->dim[0]);
RTERR_BOUND(L3_2_i<0 || L3_2_i>=(L2_1_m)->dim[1]);
IDX_PTR(L2_1_m,real)[(L2_1_m)->mod[0]*((int)L3_2_i)+(L2_1_m)->mod[1]*((int)L3_2_i)] = 1;
}
}
L_Tmp0 = L2_1_m;
}
TRACE_POP("C_make_d2_place_target");
return L_Tmp0;
}
}

/*
 * FUNCTION idx-d1range
 */
extern_c struct idx* C_idx_d1range(real L1_n1,real L1_n2,real L1_delta,struct idx* L2_0_matrix,struct srg* L2_0_srg)
{
TRACE_PUSH("C_idx_d1range");
{
struct idx* L_Tmp0;
{
real L2_1_n;
struct idx* L2_2_v;
real L2_3_x;
L2_1_n = (1+((L1_n2-L1_n1)/(real)L1_delta));
L2_1_n = ((intg)floor((double)L2_1_n));
(L2_0_matrix)->srg = L2_0_srg;
Midx_init_dim1(L2_0_matrix, L2_1_n);
RTERR_DIM(L2_0_matrix->dim[0]<=0);
Midx_maclear(L2_0_matrix, real);
L2_2_v = L2_0_matrix;
L2_3_x = L1_n1;
{
real L3_4_i;
real L_Tmp5;
L_Tmp5 = ((L2_1_n)-1);
L3_4_i = 0;
for(;
((1>0)?(L3_4_i<=L_Tmp5):(L3_4_i>=L_Tmp5));
(L3_4_i)+=1 ) {
RTERR_BOUND(L3_4_i<0 || L3_4_i>=(L2_2_v)->dim[0]);
IDX_PTR(L2_2_v,real)[(L2_2_v)->mod[0]*((int)L3_4_i)] = L2_3_x;
L2_3_x = (L2_3_x+L1_delta);
}
}
L_Tmp0 = L2_2_v;
}
TRACE_POP("C_idx_d1range");
return L_Tmp0;
}
}

/*
 * FUNCTION idx-d1squextd1
 */
extern_c char C_idx_d1squextd1(struct idx* L1_m1,struct idx* L1_m2,struct idx* L1_m3)
{
TRACE_PUSH("C_idx_d1squextd1");
{
 Midx_m1squextm1((L1_m1),(L1_m2),(L1_m3),double,double,double);
TRACE_POP("C_idx_d1squextd1");
return 0;
}
}

/*
 * FUNCTION idx-d2squextd2
 */
extern_c char C_idx_d2squextd2(struct idx* L1_m1,struct idx* L1_m2,struct idx* L1_m3)
{
TRACE_PUSH("C_idx_d2squextd2");
{
 Midx_m2squextm2((L1_m1),(L1_m2),(L1_m3),double,double,double);
TRACE_POP("C_idx_d2squextd2");
return 0;
}
}

/*
 * FUNCTION idx-d1squextd1acc
 */
extern_c char C_idx_d1squextd1acc(struct idx* L1_m1,struct idx* L1_m2,struct idx* L1_m3)
{
TRACE_PUSH("C_idx_d1squextd1acc");
{
 Midx_m1squextm1acc((L1_m1),(L1_m2),(L1_m3),double,double,double);
TRACE_POP("C_idx_d1squextd1acc");
return 0;
}
}

/*
 * FUNCTION idx-d2squextd2acc
 */
extern_c char C_idx_d2squextd2acc(struct idx* L1_m1,struct idx* L1_m2,struct idx* L1_m3)
{
TRACE_PUSH("C_idx_d2squextd2acc");
{
 Midx_m2squextm2acc((L1_m1),(L1_m2),(L1_m3),double,double,double);
TRACE_POP("C_idx_d2squextd2acc");
return 0;
}
}

/*
 * FUNCTION idx-d2squdotd1
 */
extern_c char C_idx_d2squdotd1(struct idx* L1_m1,struct idx* L1_m2,struct idx* L1_m3)
{
TRACE_PUSH("C_idx_d2squdotd1");
{
 Midx_m2squdotm1((L1_m1),(L1_m2),(L1_m3),double,double,double);
TRACE_POP("C_idx_d2squdotd1");
return 0;
}
}

/*
 * FUNCTION idx-d4squdotd2
 */
extern_c char C_idx_d4squdotd2(struct idx* L1_m1,struct idx* L1_m2,struct idx* L1_m3)
{
TRACE_PUSH("C_idx_d4squdotd2");
{
 Midx_m4squdotm2((L1_m1),(L1_m2),(L1_m3),double,double,double);
TRACE_POP("C_idx_d4squdotd2");
return 0;
}
}

/*
 * FUNCTION idx-d2squdotd1acc
 */
extern_c char C_idx_d2squdotd1acc(struct idx* L1_m1,struct idx* L1_m2,struct idx* L1_m3)
{
TRACE_PUSH("C_idx_d2squdotd1acc");
{
 Midx_m2squdotm1acc((L1_m1),(L1_m2),(L1_m3),double,double,double);
TRACE_POP("C_idx_d2squdotd1acc");
return 0;
}
}

/*
 * FUNCTION idx-d4squdotd2acc
 */
extern_c char C_idx_d4squdotd2acc(struct idx* L1_m1,struct idx* L1_m2,struct idx* L1_m3)
{
TRACE_PUSH("C_idx_d4squdotd2acc");
{
 Midx_m4squdotm2acc((L1_m1),(L1_m2),(L1_m3),double,double,double);
TRACE_POP("C_idx_d4squdotd2acc");
return 0;
}
}

/*
 * FUNCTION idx-d1squdotd1acc
 */
extern_c char C_idx_d1squdotd1acc(struct idx* L1_m1,struct idx* L1_m2,struct idx* L1_m3)
{
TRACE_PUSH("C_idx_d1squdotd1acc");
{
 Midx_m1squdotm1acc((L1_m1),(L1_m2),(L1_m3),double,double,double);
TRACE_POP("C_idx_d1squdotd1acc");
return 0;
}
}

/*
 * FUNCTION idx-d2squdotd2acc
 */
extern_c char C_idx_d2squdotd2acc(struct idx* L1_m1,struct idx* L1_m2,struct idx* L1_m3)
{
TRACE_PUSH("C_idx_d2squdotd2acc");
{
 Midx_m2squdotm2acc((L1_m1),(L1_m2),(L1_m3),double,double,double);
TRACE_POP("C_idx_d2squdotd2acc");
return 0;
}
}

/* ---------------------------------------- */

#ifndef NOLISP


/*
 * STUB idx-d2timesd2
 */
DH(X_idx_d2timesd2)
{
dharg ret;
ret.dh_idx_ptr =  C_idx_d2timesd2(a[1].dh_idx_ptr, a[2].dh_idx_ptr, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-d2timesd2
 */
DHDOC(K_idx_d2timesd2_R6259825bb29bfe4c,X_idx_d2timesd2,"C_idx_d2timesd2",0,0) = {
DH_FUNC(3),
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_REAL,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_REAL,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_REAL,
DH_RETURN,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_REAL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d1reverse
 */
DH(X_idx_d1reverse)
{
dharg ret;
ret.dh_char =  C_idx_d1reverse(a[1].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-d1reverse
 */
DHDOC(K_idx_d1reverse_Rb68ab27ba8685f22,X_idx_d1reverse,"C_idx_d1reverse",0,0) = {
DH_FUNC(1),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_WRITE),
DH_REAL,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d1fill
 */
DH(X_idx_d1fill)
{
dharg ret;
ret.dh_char =  C_idx_d1fill(a[1].dh_idx_ptr, a[2].dh_real);
return ret;
}

/*
 * DHDOC idx-d1fill
 */
DHDOC(K_idx_d1fill_R1ebfb0357fc0d4d0,X_idx_d1fill,"C_idx_d1fill",0,0) = {
DH_FUNC(2),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_REAL,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d2fill
 */
DH(X_idx_d2fill)
{
dharg ret;
ret.dh_idx_ptr =  C_idx_d2fill(a[1].dh_idx_ptr, a[2].dh_real);
return ret;
}

/*
 * DHDOC idx-d2fill
 */
DHDOC(K_idx_d2fill_R7993b26b9204d22c,X_idx_d2fill,"C_idx_d2fill",0,0) = {
DH_FUNC(2),
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_REAL,
DH_REAL,
DH_RETURN,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_REAL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d3fill
 */
DH(X_idx_d3fill)
{
dharg ret;
ret.dh_idx_ptr =  C_idx_d3fill(a[1].dh_idx_ptr, a[2].dh_real);
return ret;
}

/*
 * DHDOC idx-d3fill
 */
DHDOC(K_idx_d3fill_R7993b26b9204d22c,X_idx_d3fill,"C_idx_d3fill",0,0) = {
DH_FUNC(2),
DH_IDX(DHT_READ,3),
DH_SRG(DHT_READ),
DH_REAL,
DH_REAL,
DH_RETURN,
DH_IDX(DHT_READ,3),
DH_SRG(DHT_READ),
DH_REAL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d1dotc
 */
DH(X_idx_d1dotc)
{
dharg ret;
ret.dh_char =  C_idx_d1dotc(a[1].dh_idx_ptr, a[2].dh_real, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-d1dotc
 */
DHDOC(K_idx_d1dotc_R77b5a733aa2bd5b6,X_idx_d1dotc,"C_idx_d1dotc",0,0) = {
DH_FUNC(3),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_REAL,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d2dotc
 */
DH(X_idx_d2dotc)
{
dharg ret;
ret.dh_idx_ptr =  C_idx_d2dotc(a[1].dh_idx_ptr, a[2].dh_real, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-d2dotc
 */
DHDOC(K_idx_d2dotc_R1099a56d47efd34a,X_idx_d2dotc,"C_idx_d2dotc",0,0) = {
DH_FUNC(3),
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_REAL,
DH_REAL,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_REAL,
DH_RETURN,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_REAL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d3dotc
 */
DH(X_idx_d3dotc)
{
dharg ret;
ret.dh_idx_ptr =  C_idx_d3dotc(a[1].dh_idx_ptr, a[2].dh_real, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-d3dotc
 */
DHDOC(K_idx_d3dotc_R1099a56d47efd34a,X_idx_d3dotc,"C_idx_d3dotc",0,0) = {
DH_FUNC(3),
DH_IDX(DHT_READ,3),
DH_SRG(DHT_READ),
DH_REAL,
DH_REAL,
DH_IDX(DHT_READ,3),
DH_SRG(DHT_READ),
DH_REAL,
DH_RETURN,
DH_IDX(DHT_READ,3),
DH_SRG(DHT_READ),
DH_REAL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d1dotcacc
 */
DH(X_idx_d1dotcacc)
{
dharg ret;
ret.dh_char =  C_idx_d1dotcacc(a[1].dh_idx_ptr, a[2].dh_real, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-d1dotcacc
 */
DHDOC(K_idx_d1dotcacc_R77b5a733aa2bd5b6,X_idx_d1dotcacc,"C_idx_d1dotcacc",0,0) = {
DH_FUNC(3),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_REAL,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d2dotcacc
 */
DH(X_idx_d2dotcacc)
{
dharg ret;
ret.dh_idx_ptr =  C_idx_d2dotcacc(a[1].dh_idx_ptr, a[2].dh_real, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-d2dotcacc
 */
DHDOC(K_idx_d2dotcacc_R1099a56d47efd34a,X_idx_d2dotcacc,"C_idx_d2dotcacc",0,0) = {
DH_FUNC(3),
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_REAL,
DH_REAL,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_REAL,
DH_RETURN,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_REAL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d3dotcacc
 */
DH(X_idx_d3dotcacc)
{
dharg ret;
ret.dh_idx_ptr =  C_idx_d3dotcacc(a[1].dh_idx_ptr, a[2].dh_real, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-d3dotcacc
 */
DHDOC(K_idx_d3dotcacc_R1099a56d47efd34a,X_idx_d3dotcacc,"C_idx_d3dotcacc",0,0) = {
DH_FUNC(3),
DH_IDX(DHT_READ,3),
DH_SRG(DHT_READ),
DH_REAL,
DH_REAL,
DH_IDX(DHT_READ,3),
DH_SRG(DHT_READ),
DH_REAL,
DH_RETURN,
DH_IDX(DHT_READ,3),
DH_SRG(DHT_READ),
DH_REAL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d1addc
 */
DH(X_idx_d1addc)
{
dharg ret;
ret.dh_char =  C_idx_d1addc(a[1].dh_idx_ptr, a[2].dh_real, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-d1addc
 */
DHDOC(K_idx_d1addc_R77b5a733aa2bd5b6,X_idx_d1addc,"C_idx_d1addc",0,0) = {
DH_FUNC(3),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_REAL,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d2addc
 */
DH(X_idx_d2addc)
{
dharg ret;
ret.dh_idx_ptr =  C_idx_d2addc(a[1].dh_idx_ptr, a[2].dh_real, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-d2addc
 */
DHDOC(K_idx_d2addc_R1099a56d47efd34a,X_idx_d2addc,"C_idx_d2addc",0,0) = {
DH_FUNC(3),
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_REAL,
DH_REAL,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_REAL,
DH_RETURN,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_REAL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d3addc
 */
DH(X_idx_d3addc)
{
dharg ret;
ret.dh_idx_ptr =  C_idx_d3addc(a[1].dh_idx_ptr, a[2].dh_real, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-d3addc
 */
DHDOC(K_idx_d3addc_R1099a56d47efd34a,X_idx_d3addc,"C_idx_d3addc",0,0) = {
DH_FUNC(3),
DH_IDX(DHT_READ,3),
DH_SRG(DHT_READ),
DH_REAL,
DH_REAL,
DH_IDX(DHT_READ,3),
DH_SRG(DHT_READ),
DH_REAL,
DH_RETURN,
DH_IDX(DHT_READ,3),
DH_SRG(DHT_READ),
DH_REAL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d1lincomb
 */
DH(X_idx_d1lincomb)
{
dharg ret;
ret.dh_char =  C_idx_d1lincomb(a[1].dh_idx_ptr, a[2].dh_real, a[3].dh_idx_ptr, a[4].dh_real, a[5].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-d1lincomb
 */
DHDOC(K_idx_d1lincomb_R7349f213a325ffe5,X_idx_d1lincomb,"C_idx_d1lincomb",0,0) = {
DH_FUNC(5),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_REAL,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_REAL,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d1tanh
 */
DH(X_idx_d1tanh)
{
dharg ret;
ret.dh_char =  C_idx_d1tanh(a[1].dh_idx_ptr, a[2].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-d1tanh
 */
DHDOC(K_idx_d1tanh_R27dfa3ae057ac253,X_idx_d1tanh,"C_idx_d1tanh",0,0) = {
DH_FUNC(2),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d1inv
 */
DH(X_idx_d1inv)
{
dharg ret;
ret.dh_char =  C_idx_d1inv(a[1].dh_idx_ptr, a[2].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-d1inv
 */
DHDOC(K_idx_d1inv_R27dfa3ae057ac253,X_idx_d1inv,"C_idx_d1inv",0,0) = {
DH_FUNC(2),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d1sign
 */
DH(X_idx_d1sign)
{
dharg ret;
ret.dh_char =  C_idx_d1sign(a[1].dh_idx_ptr, a[2].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-d1sign
 */
DHDOC(K_idx_d1sign_R27dfa3ae057ac253,X_idx_d1sign,"C_idx_d1sign",0,0) = {
DH_FUNC(2),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d1clip
 */
DH(X_idx_d1clip)
{
dharg ret;
ret.dh_char =  C_idx_d1clip(a[1].dh_idx_ptr, a[2].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-d1clip
 */
DHDOC(K_idx_d1clip_R27dfa3ae057ac253,X_idx_d1clip,"C_idx_d1clip",0,0) = {
DH_FUNC(2),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d1sup
 */
DH(X_idx_d1sup)
{
dharg ret;
ret.dh_real =  C_idx_d1sup(a[1].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-d1sup
 */
DHDOC(K_idx_d1sup_Rb68ab2562afb1b0e,X_idx_d1sup,"C_idx_d1sup",0,0) = {
DH_FUNC(1),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_RETURN,
DH_REAL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d1inf
 */
DH(X_idx_d1inf)
{
dharg ret;
ret.dh_real =  C_idx_d1inf(a[1].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-d1inf
 */
DHDOC(K_idx_d1inf_Rb68ab2562afb1b0e,X_idx_d1inf,"C_idx_d1inf",0,0) = {
DH_FUNC(1),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_RETURN,
DH_REAL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d1indexmax
 */
DH(X_idx_d1indexmax)
{
dharg ret;
ret.dh_int =  C_idx_d1indexmax(a[1].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-d1indexmax
 */
DHDOC(K_idx_d1indexmax_Rb08092fe00525204,X_idx_d1indexmax,"C_idx_d1indexmax",0,0) = {
DH_FUNC(1),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_RETURN,
DH_INT,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d1indexmin
 */
DH(X_idx_d1indexmin)
{
dharg ret;
ret.dh_int =  C_idx_d1indexmin(a[1].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-d1indexmin
 */
DHDOC(K_idx_d1indexmin_Rb08092fe00525204,X_idx_d1indexmin,"C_idx_d1indexmin",0,0) = {
DH_FUNC(1),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_RETURN,
DH_INT,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d1fill-with-index
 */
DH(X_idx_d1fill_with_index)
{
dharg ret;
ret.dh_char =  C_idx_d1fill_with_index(a[1].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-d1fill-with-index
 */
DHDOC(K_idx_d1fill_with_index_Rb68ab27ba8685f22,X_idx_d1fill_with_index,"C_idx_d1fill_with_index",0,0) = {
DH_FUNC(1),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d1avg
 */
DH(X_idx_d1avg)
{
dharg ret;
ret.dh_real =  C_idx_d1avg(a[1].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-d1avg
 */
DHDOC(K_idx_d1avg_Rb68ab2562afb1b0e,X_idx_d1avg,"C_idx_d1avg",0,0) = {
DH_FUNC(1),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_RETURN,
DH_REAL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d1prod
 */
DH(X_idx_d1prod)
{
dharg ret;
ret.dh_real =  C_idx_d1prod(a[1].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-d1prod
 */
DHDOC(K_idx_d1prod_Rb68ab2562afb1b0e,X_idx_d1prod,"C_idx_d1prod",0,0) = {
DH_FUNC(1),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_RETURN,
DH_REAL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d1logsum
 */
DH(X_idx_d1logsum)
{
dharg ret;
ret.dh_real =  C_idx_d1logsum(a[1].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-d1logsum
 */
DHDOC(K_idx_d1logsum_Rb68ab2562afb1b0e,X_idx_d1logsum,"C_idx_d1logsum",0,0) = {
DH_FUNC(1),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_RETURN,
DH_REAL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d2logsum
 */
DH(X_idx_d2logsum)
{
dharg ret;
ret.dh_real =  C_idx_d2logsum(a[1].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-d2logsum
 */
DHDOC(K_idx_d2logsum_Rb68ab2562afb1b0e,X_idx_d2logsum,"C_idx_d2logsum",0,0) = {
DH_FUNC(1),
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_REAL,
DH_RETURN,
DH_REAL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d1logadd
 */
DH(X_idx_d1logadd)
{
dharg ret;
ret.dh_real =  C_idx_d1logadd(a[1].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-d1logadd
 */
DHDOC(K_idx_d1logadd_Rb68ab2562afb1b0e,X_idx_d1logadd,"C_idx_d1logadd",0,0) = {
DH_FUNC(1),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_RETURN,
DH_REAL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d2logadd
 */
DH(X_idx_d2logadd)
{
dharg ret;
ret.dh_real =  C_idx_d2logadd(a[1].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-d2logadd
 */
DHDOC(K_idx_d2logadd_Rb68ab2562afb1b0e,X_idx_d2logadd,"C_idx_d2logadd",0,0) = {
DH_FUNC(1),
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_REAL,
DH_RETURN,
DH_REAL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d1logaddb
 */
DH(X_idx_d1logaddb)
{
dharg ret;
ret.dh_real =  C_idx_d1logaddb(a[1].dh_idx_ptr, a[2].dh_real);
return ret;
}

/*
 * DHDOC idx-d1logaddb
 */
DHDOC(K_idx_d1logaddb_R1ebfb018fd5390fc,X_idx_d1logaddb,"C_idx_d1logaddb",0,0) = {
DH_FUNC(2),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_REAL,
DH_RETURN,
DH_REAL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d2logaddb
 */
DH(X_idx_d2logaddb)
{
dharg ret;
ret.dh_real =  C_idx_d2logaddb(a[1].dh_idx_ptr, a[2].dh_real);
return ret;
}

/*
 * DHDOC idx-d2logaddb
 */
DHDOC(K_idx_d2logaddb_R1ebfb018fd5390fc,X_idx_d2logaddb,"C_idx_d2logaddb",0,0) = {
DH_FUNC(2),
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_REAL,
DH_REAL,
DH_RETURN,
DH_REAL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d1logdotd1
 */
DH(X_idx_d1logdotd1)
{
dharg ret;
ret.dh_real =  C_idx_d1logdotd1(a[1].dh_idx_ptr, a[2].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-d1logdotd1
 */
DHDOC(K_idx_d1logdotd1_R27dfa38387e9867f,X_idx_d1logdotd1,"C_idx_d1logdotd1",0,0) = {
DH_FUNC(2),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_RETURN,
DH_REAL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d1blogdotd1
 */
DH(X_idx_d1blogdotd1)
{
dharg ret;
ret.dh_char =  C_idx_d1blogdotd1(a[1].dh_idx_ptr, a[2].dh_idx_ptr, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-d1blogdotd1
 */
DHDOC(K_idx_d1blogdotd1_R057580055f5ff8b0,X_idx_d1blogdotd1,"C_idx_d1blogdotd1",0,0) = {
DH_FUNC(3),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d2logdotd2
 */
DH(X_idx_d2logdotd2)
{
dharg ret;
ret.dh_real =  C_idx_d2logdotd2(a[1].dh_idx_ptr, a[2].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-d2logdotd2
 */
DHDOC(K_idx_d2logdotd2_R27dfa38387e9867f,X_idx_d2logdotd2,"C_idx_d2logdotd2",0,0) = {
DH_FUNC(2),
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_REAL,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_REAL,
DH_RETURN,
DH_REAL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d1subextd1
 */
DH(X_idx_d1subextd1)
{
dharg ret;
ret.dh_char =  C_idx_d1subextd1(a[1].dh_idx_ptr, a[2].dh_idx_ptr, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-d1subextd1
 */
DHDOC(K_idx_d1subextd1_R057580055f5ff8b0,X_idx_d1subextd1,"C_idx_d1subextd1",0,0) = {
DH_FUNC(3),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_REAL,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d1subd0
 */
DH(X_idx_d1subd0)
{
dharg ret;
ret.dh_char =  C_idx_d1subd0(a[1].dh_idx_ptr, a[2].dh_idx_ptr, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-d1subd0
 */
DHDOC(K_idx_d1subd0_R057580055f5ff8b0,X_idx_d1subd0,"C_idx_d1subd0",0,0) = {
DH_FUNC(3),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_IDX(DHT_READ,0),
DH_SRG(DHT_READ),
DH_REAL,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d1mulacc
 */
DH(X_idx_d1mulacc)
{
dharg ret;
ret.dh_idx_ptr =  C_idx_d1mulacc(a[1].dh_idx_ptr, a[2].dh_idx_ptr, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-d1mulacc
 */
DHDOC(K_idx_d1mulacc_R6259825bb29bfe4c,X_idx_d1mulacc,"C_idx_d1mulacc",0,0) = {
DH_FUNC(3),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_RETURN,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d1entropy
 */
DH(X_idx_d1entropy)
{
dharg ret;
ret.dh_real =  C_idx_d1entropy(a[1].dh_idx_ptr, a[2].dh_real);
return ret;
}

/*
 * DHDOC idx-d1entropy
 */
DHDOC(K_idx_d1entropy_R1ebfb018fd5390fc,X_idx_d1entropy,"C_idx_d1entropy",0,0) = {
DH_FUNC(2),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_REAL,
DH_RETURN,
DH_REAL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d1subsample-fast
 */
DH(X_idx_d1subsample_fast)
{
dharg ret;
ret.dh_idx_ptr =  C_idx_d1subsample_fast(a[1].dh_idx_ptr, a[2].dh_int, a[3].dh_idx_ptr, a[4].dh_srg_ptr);
return ret;
}

/*
 * DHDOC idx-d1subsample-fast
 */
DHDOC(K_idx_d1subsample_fast_R3bb0931c2636638a,X_idx_d1subsample_fast,"C_idx_d1subsample_fast",0,0) = {
DH_FUNC(2),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_INT,
DH_TEMPS(2),
DH_IDX(DHT_WRITE,1),DH_REAL,
DH_SRG(DHT_WRITE), DH_REAL,
DH_END_TEMPS,
DH_RETURN,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d3dotd3
 */
DH(X_idx_d3dotd3)
{
dharg ret;
ret.dh_real =  C_idx_d3dotd3(a[1].dh_idx_ptr, a[2].dh_idx_ptr, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-d3dotd3
 */
DHDOC(K_idx_d3dotd3_R05758028ddccbc9c,X_idx_d3dotd3,"C_idx_d3dotd3",0,0) = {
DH_FUNC(3),
DH_IDX(DHT_READ,3),
DH_SRG(DHT_READ),
DH_REAL,
DH_IDX(DHT_READ,3),
DH_SRG(DHT_READ),
DH_REAL,
DH_IDX(DHT_READ,0),
DH_SRG(DHT_WRITE),
DH_REAL,
DH_RETURN,
DH_REAL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d3dotd2
 */
DH(X_idx_d3dotd2)
{
dharg ret;
ret.dh_idx_ptr =  C_idx_d3dotd2(a[1].dh_idx_ptr, a[2].dh_idx_ptr, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-d3dotd2
 */
DHDOC(K_idx_d3dotd2_R6259825bb29bfe4c,X_idx_d3dotd2,"C_idx_d3dotd2",0,0) = {
DH_FUNC(3),
DH_IDX(DHT_READ,3),
DH_SRG(DHT_READ),
DH_REAL,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_REAL,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_RETURN,
DH_IDX(DHT_READ,3),
DH_SRG(DHT_READ),
DH_REAL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d3dotd1
 */
DH(X_idx_d3dotd1)
{
dharg ret;
ret.dh_idx_ptr =  C_idx_d3dotd1(a[1].dh_idx_ptr, a[2].dh_idx_ptr, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-d3dotd1
 */
DHDOC(K_idx_d3dotd1_R6259825bb29bfe4c,X_idx_d3dotd1,"C_idx_d3dotd1",0,0) = {
DH_FUNC(3),
DH_IDX(DHT_READ,3),
DH_SRG(DHT_READ),
DH_REAL,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_WRITE),
DH_REAL,
DH_RETURN,
DH_IDX(DHT_READ,3),
DH_SRG(DHT_READ),
DH_REAL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d3dotd1acc
 */
DH(X_idx_d3dotd1acc)
{
dharg ret;
ret.dh_idx_ptr =  C_idx_d3dotd1acc(a[1].dh_idx_ptr, a[2].dh_idx_ptr, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-d3dotd1acc
 */
DHDOC(K_idx_d3dotd1acc_R6259825bb29bfe4c,X_idx_d3dotd1acc,"C_idx_d3dotd1acc",0,0) = {
DH_FUNC(3),
DH_IDX(DHT_READ,3),
DH_SRG(DHT_READ),
DH_REAL,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_REAL,
DH_RETURN,
DH_IDX(DHT_READ,3),
DH_SRG(DHT_READ),
DH_REAL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d3extd1
 */
DH(X_idx_d3extd1)
{
dharg ret;
ret.dh_idx_ptr =  C_idx_d3extd1(a[1].dh_idx_ptr, a[2].dh_idx_ptr, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-d3extd1
 */
DHDOC(K_idx_d3extd1_R6259825bb29bfe4c,X_idx_d3extd1,"C_idx_d3extd1",0,0) = {
DH_FUNC(3),
DH_IDX(DHT_READ,3),
DH_SRG(DHT_READ),
DH_REAL,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_IDX(DHT_READ,4),
DH_SRG(DHT_READ),
DH_REAL,
DH_RETURN,
DH_IDX(DHT_READ,4),
DH_SRG(DHT_READ),
DH_REAL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d1extd3
 */
DH(X_idx_d1extd3)
{
dharg ret;
ret.dh_idx_ptr =  C_idx_d1extd3(a[1].dh_idx_ptr, a[2].dh_idx_ptr, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-d1extd3
 */
DHDOC(K_idx_d1extd3_R6259825bb29bfe4c,X_idx_d1extd3,"C_idx_d1extd3",0,0) = {
DH_FUNC(3),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_IDX(DHT_READ,3),
DH_SRG(DHT_READ),
DH_REAL,
DH_IDX(DHT_READ,4),
DH_SRG(DHT_READ),
DH_REAL,
DH_RETURN,
DH_IDX(DHT_READ,4),
DH_SRG(DHT_READ),
DH_REAL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d1extd2
 */
DH(X_idx_d1extd2)
{
dharg ret;
ret.dh_idx_ptr =  C_idx_d1extd2(a[1].dh_idx_ptr, a[2].dh_idx_ptr, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-d1extd2
 */
DHDOC(K_idx_d1extd2_R6259825bb29bfe4c,X_idx_d1extd2,"C_idx_d1extd2",0,0) = {
DH_FUNC(3),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_REAL,
DH_IDX(DHT_READ,3),
DH_SRG(DHT_READ),
DH_REAL,
DH_RETURN,
DH_IDX(DHT_READ,3),
DH_SRG(DHT_READ),
DH_REAL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d4dotd1
 */
DH(X_idx_d4dotd1)
{
dharg ret;
ret.dh_idx_ptr =  C_idx_d4dotd1(a[1].dh_idx_ptr, a[2].dh_idx_ptr, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-d4dotd1
 */
DHDOC(K_idx_d4dotd1_R6259825bb29bfe4c,X_idx_d4dotd1,"C_idx_d4dotd1",0,0) = {
DH_FUNC(3),
DH_IDX(DHT_READ,4),
DH_SRG(DHT_READ),
DH_REAL,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_IDX(DHT_READ,3),
DH_SRG(DHT_WRITE),
DH_REAL,
DH_RETURN,
DH_IDX(DHT_READ,4),
DH_SRG(DHT_READ),
DH_REAL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d4dotd1acc
 */
DH(X_idx_d4dotd1acc)
{
dharg ret;
ret.dh_idx_ptr =  C_idx_d4dotd1acc(a[1].dh_idx_ptr, a[2].dh_idx_ptr, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-d4dotd1acc
 */
DHDOC(K_idx_d4dotd1acc_R6259825bb29bfe4c,X_idx_d4dotd1acc,"C_idx_d4dotd1acc",0,0) = {
DH_FUNC(3),
DH_IDX(DHT_READ,4),
DH_SRG(DHT_READ),
DH_REAL,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_IDX(DHT_READ,3),
DH_SRG(DHT_READ),
DH_REAL,
DH_RETURN,
DH_IDX(DHT_READ,4),
DH_SRG(DHT_READ),
DH_REAL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB make-d2-place-target
 */
DH(X_make_d2_place_target)
{
dharg ret;
ret.dh_idx_ptr =  C_make_d2_place_target(a[1].dh_int, a[2].dh_idx_ptr, a[3].dh_srg_ptr);
return ret;
}

/*
 * DHDOC make-d2-place-target
 */
DHDOC(K_make_d2_place_target_Raae582c98b24fefb,X_make_d2_place_target,"C_make_d2_place_target",0,0) = {
DH_FUNC(1),
DH_INT,
DH_TEMPS(2),
DH_IDX(DHT_WRITE,2),DH_REAL,
DH_SRG(DHT_WRITE), DH_REAL,
DH_END_TEMPS,
DH_RETURN,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_WRITE),
DH_REAL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d1range
 */
DH(X_idx_d1range)
{
dharg ret;
ret.dh_idx_ptr =  C_idx_d1range(a[1].dh_real, a[2].dh_real, a[3].dh_real, a[4].dh_idx_ptr, a[5].dh_srg_ptr);
return ret;
}

/*
 * DHDOC idx-d1range
 */
DHDOC(K_idx_d1range_Rbe0bdcad36c56633,X_idx_d1range,"C_idx_d1range",0,0) = {
DH_FUNC(3),
DH_REAL,
DH_REAL,
DH_REAL,
DH_TEMPS(2),
DH_IDX(DHT_WRITE,1),DH_REAL,
DH_SRG(DHT_WRITE), DH_REAL,
DH_END_TEMPS,
DH_RETURN,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_WRITE),
DH_REAL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d1squextd1
 */
DH(X_idx_d1squextd1)
{
dharg ret;
ret.dh_char =  C_idx_d1squextd1(a[1].dh_idx_ptr, a[2].dh_idx_ptr, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-d1squextd1
 */
DHDOC(K_idx_d1squextd1_R057580055f5ff8b0,X_idx_d1squextd1,"C_idx_d1squextd1",0,0) = {
DH_FUNC(3),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_REAL,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d2squextd2
 */
DH(X_idx_d2squextd2)
{
dharg ret;
ret.dh_char =  C_idx_d2squextd2(a[1].dh_idx_ptr, a[2].dh_idx_ptr, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-d2squextd2
 */
DHDOC(K_idx_d2squextd2_R057580055f5ff8b0,X_idx_d2squextd2,"C_idx_d2squextd2",0,0) = {
DH_FUNC(3),
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_REAL,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_REAL,
DH_IDX(DHT_READ,4),
DH_SRG(DHT_READ),
DH_REAL,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d1squextd1acc
 */
DH(X_idx_d1squextd1acc)
{
dharg ret;
ret.dh_char =  C_idx_d1squextd1acc(a[1].dh_idx_ptr, a[2].dh_idx_ptr, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-d1squextd1acc
 */
DHDOC(K_idx_d1squextd1acc_R057580055f5ff8b0,X_idx_d1squextd1acc,"C_idx_d1squextd1acc",0,0) = {
DH_FUNC(3),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_REAL,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d2squextd2acc
 */
DH(X_idx_d2squextd2acc)
{
dharg ret;
ret.dh_char =  C_idx_d2squextd2acc(a[1].dh_idx_ptr, a[2].dh_idx_ptr, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-d2squextd2acc
 */
DHDOC(K_idx_d2squextd2acc_R057580055f5ff8b0,X_idx_d2squextd2acc,"C_idx_d2squextd2acc",0,0) = {
DH_FUNC(3),
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_REAL,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_REAL,
DH_IDX(DHT_READ,4),
DH_SRG(DHT_READ),
DH_REAL,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d2squdotd1
 */
DH(X_idx_d2squdotd1)
{
dharg ret;
ret.dh_char =  C_idx_d2squdotd1(a[1].dh_idx_ptr, a[2].dh_idx_ptr, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-d2squdotd1
 */
DHDOC(K_idx_d2squdotd1_R057580055f5ff8b0,X_idx_d2squdotd1,"C_idx_d2squdotd1",0,0) = {
DH_FUNC(3),
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_REAL,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d4squdotd2
 */
DH(X_idx_d4squdotd2)
{
dharg ret;
ret.dh_char =  C_idx_d4squdotd2(a[1].dh_idx_ptr, a[2].dh_idx_ptr, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-d4squdotd2
 */
DHDOC(K_idx_d4squdotd2_R057580055f5ff8b0,X_idx_d4squdotd2,"C_idx_d4squdotd2",0,0) = {
DH_FUNC(3),
DH_IDX(DHT_READ,4),
DH_SRG(DHT_READ),
DH_REAL,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_REAL,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_REAL,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d2squdotd1acc
 */
DH(X_idx_d2squdotd1acc)
{
dharg ret;
ret.dh_char =  C_idx_d2squdotd1acc(a[1].dh_idx_ptr, a[2].dh_idx_ptr, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-d2squdotd1acc
 */
DHDOC(K_idx_d2squdotd1acc_R057580055f5ff8b0,X_idx_d2squdotd1acc,"C_idx_d2squdotd1acc",0,0) = {
DH_FUNC(3),
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_REAL,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d4squdotd2acc
 */
DH(X_idx_d4squdotd2acc)
{
dharg ret;
ret.dh_char =  C_idx_d4squdotd2acc(a[1].dh_idx_ptr, a[2].dh_idx_ptr, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-d4squdotd2acc
 */
DHDOC(K_idx_d4squdotd2acc_R057580055f5ff8b0,X_idx_d4squdotd2acc,"C_idx_d4squdotd2acc",0,0) = {
DH_FUNC(3),
DH_IDX(DHT_READ,4),
DH_SRG(DHT_READ),
DH_REAL,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_REAL,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_REAL,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d1squdotd1acc
 */
DH(X_idx_d1squdotd1acc)
{
dharg ret;
ret.dh_char =  C_idx_d1squdotd1acc(a[1].dh_idx_ptr, a[2].dh_idx_ptr, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-d1squdotd1acc
 */
DHDOC(K_idx_d1squdotd1acc_R057580055f5ff8b0,X_idx_d1squdotd1acc,"C_idx_d1squdotd1acc",0,0) = {
DH_FUNC(3),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_IDX(DHT_READ,0),
DH_SRG(DHT_READ),
DH_REAL,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d2squdotd2acc
 */
DH(X_idx_d2squdotd2acc)
{
dharg ret;
ret.dh_char =  C_idx_d2squdotd2acc(a[1].dh_idx_ptr, a[2].dh_idx_ptr, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-d2squdotd2acc
 */
DHDOC(K_idx_d2squdotd2acc_R057580055f5ff8b0,X_idx_d2squdotd2acc,"C_idx_d2squdotd2acc",0,0) = {
DH_FUNC(3),
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_REAL,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_REAL,
DH_IDX(DHT_READ,0),
DH_SRG(DHT_READ),
DH_REAL,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * INIT FUNCTION
 */
extern_c void init_idx_double(void)
{
 dh_define("idx-d2timesd2", &K_idx_d2timesd2_R6259825bb29bfe4c); 
 dh_define("idx-d1reverse", &K_idx_d1reverse_Rb68ab27ba8685f22); 
 dh_define("idx-d1fill", &K_idx_d1fill_R1ebfb0357fc0d4d0); 
 dh_define("idx-d2fill", &K_idx_d2fill_R7993b26b9204d22c); 
 dh_define("idx-d3fill", &K_idx_d3fill_R7993b26b9204d22c); 
 dh_define("idx-d1dotc", &K_idx_d1dotc_R77b5a733aa2bd5b6); 
 dh_define("idx-d2dotc", &K_idx_d2dotc_R1099a56d47efd34a); 
 dh_define("idx-d3dotc", &K_idx_d3dotc_R1099a56d47efd34a); 
 dh_define("idx-d1dotcacc", &K_idx_d1dotcacc_R77b5a733aa2bd5b6); 
 dh_define("idx-d2dotcacc", &K_idx_d2dotcacc_R1099a56d47efd34a); 
 dh_define("idx-d3dotcacc", &K_idx_d3dotcacc_R1099a56d47efd34a); 
 dh_define("idx-d1addc", &K_idx_d1addc_R77b5a733aa2bd5b6); 
 dh_define("idx-d2addc", &K_idx_d2addc_R1099a56d47efd34a); 
 dh_define("idx-d3addc", &K_idx_d3addc_R1099a56d47efd34a); 
 dh_define("idx-d1lincomb", &K_idx_d1lincomb_R7349f213a325ffe5); 
 dh_define("idx-d1tanh", &K_idx_d1tanh_R27dfa3ae057ac253); 
 dh_define("idx-d1inv", &K_idx_d1inv_R27dfa3ae057ac253); 
 dh_define("idx-d1sign", &K_idx_d1sign_R27dfa3ae057ac253); 
 dh_define("idx-d1clip", &K_idx_d1clip_R27dfa3ae057ac253); 
 dh_define("idx-d1sup", &K_idx_d1sup_Rb68ab2562afb1b0e); 
 dh_define("idx-d1inf", &K_idx_d1inf_Rb68ab2562afb1b0e); 
 dh_define("idx-d1indexmax", &K_idx_d1indexmax_Rb08092fe00525204); 
 dh_define("idx-d1indexmin", &K_idx_d1indexmin_Rb08092fe00525204); 
 dh_define("idx-d1fill-with-index", &K_idx_d1fill_with_index_Rb68ab27ba8685f22); 
 dh_define("idx-d1avg", &K_idx_d1avg_Rb68ab2562afb1b0e); 
 dh_define("idx-d1prod", &K_idx_d1prod_Rb68ab2562afb1b0e); 
 dh_define("idx-d1logsum", &K_idx_d1logsum_Rb68ab2562afb1b0e); 
 dh_define("idx-d2logsum", &K_idx_d2logsum_Rb68ab2562afb1b0e); 
 dh_define("idx-d1logadd", &K_idx_d1logadd_Rb68ab2562afb1b0e); 
 dh_define("idx-d2logadd", &K_idx_d2logadd_Rb68ab2562afb1b0e); 
 dh_define("idx-d1logaddb", &K_idx_d1logaddb_R1ebfb018fd5390fc); 
 dh_define("idx-d2logaddb", &K_idx_d2logaddb_R1ebfb018fd5390fc); 
 dh_define("idx-d1logdotd1", &K_idx_d1logdotd1_R27dfa38387e9867f); 
 dh_define("idx-d1blogdotd1", &K_idx_d1blogdotd1_R057580055f5ff8b0); 
 dh_define("idx-d2logdotd2", &K_idx_d2logdotd2_R27dfa38387e9867f); 
 dh_define("idx-d1subextd1", &K_idx_d1subextd1_R057580055f5ff8b0); 
 dh_define("idx-d1subd0", &K_idx_d1subd0_R057580055f5ff8b0); 
 dh_define("idx-d1mulacc", &K_idx_d1mulacc_R6259825bb29bfe4c); 
 dh_define("idx-d1entropy", &K_idx_d1entropy_R1ebfb018fd5390fc); 
 dh_define("idx-d1subsample-fast", &K_idx_d1subsample_fast_R3bb0931c2636638a); 
 dh_define("idx-d3dotd3", &K_idx_d3dotd3_R05758028ddccbc9c); 
 dh_define("idx-d3dotd2", &K_idx_d3dotd2_R6259825bb29bfe4c); 
 dh_define("idx-d3dotd1", &K_idx_d3dotd1_R6259825bb29bfe4c); 
 dh_define("idx-d3dotd1acc", &K_idx_d3dotd1acc_R6259825bb29bfe4c); 
 dh_define("idx-d3extd1", &K_idx_d3extd1_R6259825bb29bfe4c); 
 dh_define("idx-d1extd3", &K_idx_d1extd3_R6259825bb29bfe4c); 
 dh_define("idx-d1extd2", &K_idx_d1extd2_R6259825bb29bfe4c); 
 dh_define("idx-d4dotd1", &K_idx_d4dotd1_R6259825bb29bfe4c); 
 dh_define("idx-d4dotd1acc", &K_idx_d4dotd1acc_R6259825bb29bfe4c); 
 dh_define("make-d2-place-target", &K_make_d2_place_target_Raae582c98b24fefb); 
 dh_define("idx-d1range", &K_idx_d1range_Rbe0bdcad36c56633); 
 dh_define("idx-d1squextd1", &K_idx_d1squextd1_R057580055f5ff8b0); 
 dh_define("idx-d2squextd2", &K_idx_d2squextd2_R057580055f5ff8b0); 
 dh_define("idx-d1squextd1acc", &K_idx_d1squextd1acc_R057580055f5ff8b0); 
 dh_define("idx-d2squextd2acc", &K_idx_d2squextd2acc_R057580055f5ff8b0); 
 dh_define("idx-d2squdotd1", &K_idx_d2squdotd1_R057580055f5ff8b0); 
 dh_define("idx-d4squdotd2", &K_idx_d4squdotd2_R057580055f5ff8b0); 
 dh_define("idx-d2squdotd1acc", &K_idx_d2squdotd1acc_R057580055f5ff8b0); 
 dh_define("idx-d4squdotd2acc", &K_idx_d4squdotd2acc_R057580055f5ff8b0); 
 dh_define("idx-d1squdotd1acc", &K_idx_d1squdotd1acc_R057580055f5ff8b0); 
 dh_define("idx-d2squdotd2acc", &K_idx_d2squdotd2acc_R057580055f5ff8b0); 
}

int majver_idx_double = 40;
int minver_idx_double = 10;


#endif

