/* WARNING: Automatically generated code.
 * This code has been generated by the DH compiler.
 */
#ifdef HAVE_CONFIG_H
# include "lushconf.h"
#endif

/*
 * LUSH HEADERS
 */
#include "header.h"
#include "dh.h"
#include "idxmac.h"
#include "idxops.h"
#include "check_func.h"



/* ---------------------------------------- */


/*
 * FUNCTION idx-i1addc
 */
extern_c char C_idx_i1addc(struct idx* L1_m1,intg L1_c,struct idx* L1_m2)
{
TRACE_PUSH("C_idx_i1addc");
{
{
RTERR_LOOPDIM((L1_m2)->dim[0] != (L1_m1)->dim[0]);
Midx_begin_bloop2(L2_m1i, L1_m1,L2_m2i, L1_m2,intg) {
*IDX_PTR(&L2_m2i,intg) = ( *IDX_PTR(&L2_m1i,intg)+L1_c);
} Midx_end_bloop2(L2_m1i, L1_m1,L2_m2i, L1_m2,intg);
}
TRACE_POP("C_idx_i1addc");
return 0;
}
}

/*
 * FUNCTION idx-i2addc
 */
extern_c char C_idx_i2addc(struct idx* L1_m1,intg L1_c,struct idx* L1_m2)
{
TRACE_PUSH("C_idx_i2addc");
{
{
RTERR_LOOPDIM((L1_m2)->dim[0] != (L1_m1)->dim[0]);
Midx_begin_bloop2(L2_m1i, L1_m1,L2_m2i, L1_m2,intg) {
{
RTERR_LOOPDIM((&L2_m2i)->dim[0] != (&L2_m1i)->dim[0]);
Midx_begin_bloop2(L3_m1ij, &L2_m1i,L3_m2ij, &L2_m2i,intg) {
*IDX_PTR(&L3_m2ij,intg) = ( *IDX_PTR(&L3_m1ij,intg)+L1_c);
} Midx_end_bloop2(L3_m1ij, &L2_m1i,L3_m2ij, &L2_m2i,intg);
}
} Midx_end_bloop2(L2_m1i, L1_m1,L2_m2i, L1_m2,intg);
}
TRACE_POP("C_idx_i2addc");
return 0;
}
}

/*
 * FUNCTION idx-i1max
 */
extern_c intg C_idx_i1max(struct idx* L1_m)
{
TRACE_PUSH("C_idx_i1max");
{
intg L_Tmp0;
{
intg L2_1_v;
RTERR_BOUND(0>=(L1_m)->dim[0]);
L2_1_v = IDX_PTR(L1_m,intg)[(L1_m)->mod[0]*((int)0)];
{ register int *mp;
  register int i, jmax = (L1_m)->dim[0];
  register int imat1_m0 = (L1_m)->mod[0];
  mp = IDX_PTR((L1_m),int);
  for (i=0; i <jmax; i++){;
if ((*mp)>(L2_1_v)) { L2_1_v = *mp; }
    mp += imat1_m0;
  } }
L_Tmp0 = L2_1_v;
}
TRACE_POP("C_idx_i1max");
return L_Tmp0;
}
}

/*
 * FUNCTION idx-i1min
 */
extern_c intg C_idx_i1min(struct idx* L1_m)
{
TRACE_PUSH("C_idx_i1min");
{
intg L_Tmp0;
{
intg L2_1_v;
RTERR_BOUND(0>=(L1_m)->dim[0]);
L2_1_v = IDX_PTR(L1_m,intg)[(L1_m)->mod[0]*((int)0)];
{ register int *mp;
  register int i, jmax = (L1_m)->dim[0];
  register int imat1_m0 = (L1_m)->mod[0];
  mp = IDX_PTR((L1_m),int);
  for (i=0; i <jmax; i++){;
if ((*mp)<(L2_1_v)) { L2_1_v = *mp; }
    mp += imat1_m0;
  } }
L_Tmp0 = L2_1_v;
}
TRACE_POP("C_idx_i1min");
return L_Tmp0;
}
}

/*
 * FUNCTION idx-i1fill
 */
extern_c char C_idx_i1fill(struct idx* L1_m,intg L1_c)
{
TRACE_PUSH("C_idx_i1fill");
{
{
intg _i_max = (L1_m)->dim[0];
intg _L1_m_mod0 = (L1_m)->mod[0];
{
intg i;
intg *mp = IDX_PTR((L1_m),intg);
for (i=0; i<_i_max; i++) {
*mp = (L1_c);
mp += _L1_m_mod0;
}
}}
TRACE_POP("C_idx_i1fill");
return 0;
}
}

/*
 * FUNCTION idx-i2fill
 */
extern_c char C_idx_i2fill(struct idx* L1_m,intg L1_c)
{
TRACE_PUSH("C_idx_i2fill");
{
{
intg _i_max = (L1_m)->dim[0];
intg _L1_m_mod0 = (L1_m)->mod[0];
intg _j_max = (L1_m)->dim[1];
intg _L1_m_mod1 = (L1_m)->mod[1];
{
intg i;
intg *_L1_m_loop_i = IDX_PTR((L1_m),intg);
for (i=0; i<_i_max; i++) {
intg j;
intg *mp = _L1_m_loop_i;
for (j=0; j<_j_max; j++) {
*mp = (L1_c);
mp += _L1_m_mod1;
}
_L1_m_loop_i += _L1_m_mod0;
}
}}
TRACE_POP("C_idx_i2fill");
return 0;
}
}

/*
 * FUNCTION idx-i1fill-with-index
 */
extern_c char C_idx_i1fill_with_index(struct idx* L1_m)
{
TRACE_PUSH("C_idx_i1fill_with_index");
{
{ register int *mp;
  register int i, jmax = (L1_m)->dim[0];
  register int imat1_m0 = (L1_m)->mod[0];
  mp = IDX_PTR((L1_m),int);
  for (i=0; i <jmax; i++){;
*mp = (int)i;
    mp += imat1_m0;
  } }
TRACE_POP("C_idx_i1fill_with_index");
return 0;
}
}

/*
 * FUNCTION random-permute
 */
extern_c char C_random_permute(struct idx* L1_perm_vector)
{
TRACE_PUSH("C_random_permute");
{
char L_Tmp0;
{
real L2_1_n;
L2_1_n = (L1_perm_vector)->dim[0];
{
intg L3_2_i;
L3_2_i = 0;
{
Midx_begin_bloop1(L4_pi, L1_perm_vector,intg) {
{
{
real L6_3_j;
real L6_4_v;
L6_3_j = (((L2_1_n) - (L3_2_i)) * Frand() + (L3_2_i));
L6_3_j = ((intg)floor((double)L6_3_j));
RTERR_BOUND(L6_3_j<0 || L6_3_j>=(L1_perm_vector)->dim[0]);
L6_4_v = IDX_PTR(L1_perm_vector,intg)[(L1_perm_vector)->mod[0]*((int)L6_3_j)];
RTERR_BOUND(L6_3_j<0 || L6_3_j>=(L1_perm_vector)->dim[0]);
IDX_PTR(L1_perm_vector,intg)[(L1_perm_vector)->mod[0]*((int)L6_3_j)] =  *IDX_PTR(&L4_pi,intg);
*IDX_PTR(&L4_pi,intg) = L6_4_v;
}
L3_2_i = (L3_2_i+1);
}
} Midx_end_bloop1(L4_pi, L1_perm_vector,intg);
}
}
L_Tmp0 = 0;
}
TRACE_POP("C_random_permute");
return 0;
}
}

/*
 * FUNCTION fast-multinomial-sample
 */
extern_c intg C_fast_multinomial_sample(struct idx* L1_cp)
{
TRACE_PUSH("C_fast_multinomial_sample");
{
intg L_Tmp0;
{
intg L2_1_i;
intg L2_2_n;
L2_1_i = 0;
L2_2_n = (L1_cp)->dim[0];

        {
          /* result in interval [0,1], which may include 1 */
          float u = Frand(); 
          int mod = (L1_cp)->mod[0];
          float *cpp = IDX_PTR((L1_cp),flt);
          int mini=0, maxi=(L2_2_n), middle=0.5*(L2_2_n);
          float middle_value;
          while (mini < maxi-1) {
            middle_value = cpp[middle*mod];
            if (u < middle_value) {
              maxi = middle;
            } else {
              mini = middle;
            }
            middle = 0.5 * (mini+maxi);
          }
          (L2_1_i) = middle;
        }
L_Tmp0 = L2_1_i;
}
TRACE_POP("C_fast_multinomial_sample");
return L_Tmp0;
}
}

/*
 * FUNCTION multinomial-sample
 */
extern_c intg C_multinomial_sample(struct idx* L1_p)
{
TRACE_PUSH("C_multinomial_sample");
{
intg L_Tmp0;
{
intg L2_1_i;
intg L2_2_n;
L2_1_i = 0;
L2_2_n = (L1_p)->dim[0];

        {
          float u = Frand(); /* result in interval [0,1], which may include 1 */
          int mod = (L1_p)->mod[0];
          float *pi = IDX_PTR((L1_p),flt);
          float s = *pi;
          int nm1 = (L2_2_n) - 1;
          
        ms_loop:
          if (s >= u) goto ms_end;
          (L2_1_i)++;
          if ((L2_1_i) >= nm1) goto ms_end;
          pi+=mod;
          s += *pi;
          goto ms_loop;
        }
        ms_end:;
L_Tmp0 = L2_1_i;
}
TRACE_POP("C_multinomial_sample");
return L_Tmp0;
}
}

/*
 * FUNCTION distribution2cumulative
 */
extern_c char C_distribution2cumulative(struct idx* L1_p,struct idx* L1_cp)
{
TRACE_PUSH("C_distribution2cumulative");
{
{
real L2_0_s;
L2_0_s = 0;
{
RTERR_LOOPDIM((L1_cp)->dim[0] != (L1_p)->dim[0]);
Midx_begin_bloop2(L3_pi, L1_p,L3_cpi, L1_cp,flt) {
*IDX_PTR(&L3_cpi,flt) = L2_0_s;
L2_0_s = (L2_0_s+ *IDX_PTR(&L3_pi,flt));
} Midx_end_bloop2(L3_pi, L1_p,L3_cpi, L1_cp,flt);
}
}
TRACE_POP("C_distribution2cumulative");
return 0;
}
}

/*
 * FUNCTION element-in-set
 */
extern_c char C_element_in_set(intg L1_e,struct idx* L1_the_set)
{
TRACE_PUSH("C_element_in_set");
{
char L_Tmp0;
{
char L2_1_in_set;
L2_1_in_set = 0;
{
Midx_begin_bloop1(L3_ei, L1_the_set,intg) {
 if (( *IDX_PTR(&L3_ei,intg)==L1_e)) { 
L2_1_in_set = 1;
 } 
} Midx_end_bloop1(L3_ei, L1_the_set,intg);
}
L_Tmp0 = L2_1_in_set;
}
TRACE_POP("C_element_in_set");
return L_Tmp0;
}
}

/* ---------------------------------------- */

#ifndef NOLISP


/*
 * STUB idx-i1addc
 */
DH(X_idx_i1addc)
{
dharg ret;
ret.dh_char =  C_idx_i1addc(a[1].dh_idx_ptr, a[2].dh_int, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-i1addc
 */
DHDOC(K_idx_i1addc_Rd64e6f89c82697ce,X_idx_i1addc,"C_idx_i1addc",0,0) = {
DH_FUNC(3),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_INT,
DH_INT,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_INT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-i2addc
 */
DH(X_idx_i2addc)
{
dharg ret;
ret.dh_char =  C_idx_i2addc(a[1].dh_idx_ptr, a[2].dh_int, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-i2addc
 */
DHDOC(K_idx_i2addc_Rd64e6f89c82697ce,X_idx_i2addc,"C_idx_i2addc",0,0) = {
DH_FUNC(3),
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_INT,
DH_INT,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_INT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-i1max
 */
DH(X_idx_i1max)
{
dharg ret;
ret.dh_int =  C_idx_i1max(a[1].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-i1max
 */
DHDOC(K_idx_i1max_R70c7070c978097c3,X_idx_i1max,"C_idx_i1max",0,0) = {
DH_FUNC(1),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_INT,
DH_RETURN,
DH_INT,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-i1min
 */
DH(X_idx_i1min)
{
dharg ret;
ret.dh_int =  C_idx_i1min(a[1].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-i1min
 */
DHDOC(K_idx_i1min_R70c7070c978097c3,X_idx_i1min,"C_idx_i1min",0,0) = {
DH_FUNC(1),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_INT,
DH_RETURN,
DH_INT,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-i1fill
 */
DH(X_idx_i1fill)
{
dharg ret;
ret.dh_char =  C_idx_i1fill(a[1].dh_idx_ptr, a[2].dh_int);
return ret;
}

/*
 * DHDOC idx-i1fill
 */
DHDOC(K_idx_i1fill_Rae619e91052f170f,X_idx_i1fill,"C_idx_i1fill",0,0) = {
DH_FUNC(2),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_INT,
DH_INT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-i2fill
 */
DH(X_idx_i2fill)
{
dharg ret;
ret.dh_char =  C_idx_i2fill(a[1].dh_idx_ptr, a[2].dh_int);
return ret;
}

/*
 * DHDOC idx-i2fill
 */
DHDOC(K_idx_i2fill_Rae619e91052f170f,X_idx_i2fill,"C_idx_i2fill",0,0) = {
DH_FUNC(2),
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_INT,
DH_INT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-i1fill-with-index
 */
DH(X_idx_i1fill_with_index)
{
dharg ret;
ret.dh_char =  C_idx_i1fill_with_index(a[1].dh_idx_ptr);
return ret;
}

/*
 * DHDOC idx-i1fill-with-index
 */
DHDOC(K_idx_i1fill_with_index_R76cd27893fba9ae5,X_idx_i1fill_with_index,"C_idx_i1fill_with_index",0,0) = {
DH_FUNC(1),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_INT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB random-permute
 */
DH(X_random_permute)
{
dharg ret;
ret.dh_char =  C_random_permute(a[1].dh_idx_ptr);
return ret;
}

/*
 * DHDOC random-permute
 */
DHDOC(K_random_permute_R76cd27893fba9ae5,X_random_permute,"C_random_permute",0,0) = {
DH_FUNC(1),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_WRITE),
DH_INT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB fast-multinomial-sample
 */
DH(X_fast_multinomial_sample)
{
dharg ret;
ret.dh_int =  C_fast_multinomial_sample(a[1].dh_idx_ptr);
return ret;
}

/*
 * DHDOC fast-multinomial-sample
 */
DHDOC(K_fast_multinomial_sample_Ra6981d6c310d95e3,X_fast_multinomial_sample,"C_fast_multinomial_sample",0,0) = {
DH_FUNC(1),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_FLT,
DH_RETURN,
DH_INT,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB multinomial-sample
 */
DH(X_multinomial_sample)
{
dharg ret;
ret.dh_int =  C_multinomial_sample(a[1].dh_idx_ptr);
return ret;
}

/*
 * DHDOC multinomial-sample
 */
DHDOC(K_multinomial_sample_Ra6981d6c310d95e3,X_multinomial_sample,"C_multinomial_sample",0,0) = {
DH_FUNC(1),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_FLT,
DH_RETURN,
DH_INT,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB distribution2cumulative
 */
DH(X_distribution2cumulative)
{
dharg ret;
ret.dh_char =  C_distribution2cumulative(a[1].dh_idx_ptr, a[2].dh_idx_ptr);
return ret;
}

/*
 * DHDOC distribution2cumulative
 */
DHDOC(K_distribution2cumulative_R1df63318569a8a7a,X_distribution2cumulative,"C_distribution2cumulative",0,0) = {
DH_FUNC(2),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_FLT,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_FLT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB element-in-set
 */
DH(X_element_in_set)
{
dharg ret;
ret.dh_char =  C_element_in_set(a[1].dh_int, a[2].dh_idx_ptr);
return ret;
}

/*
 * DHDOC element-in-set
 */
DHDOC(K_element_in_set_Rf5fa1be8cd48ba32,X_element_in_set,"C_element_in_set",0,0) = {
DH_FUNC(2),
DH_INT,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_INT,
DH_RETURN,
DH_BOOL,
DH_END_FUNC,
DH_NIL
};

/*
 * INIT FUNCTION
 */
extern_c void init_idx_int(void)
{
 dh_define("idx-i1addc", &K_idx_i1addc_Rd64e6f89c82697ce); 
 dh_define("idx-i2addc", &K_idx_i2addc_Rd64e6f89c82697ce); 
 dh_define("idx-i1max", &K_idx_i1max_R70c7070c978097c3); 
 dh_define("idx-i1min", &K_idx_i1min_R70c7070c978097c3); 
 dh_define("idx-i1fill", &K_idx_i1fill_Rae619e91052f170f); 
 dh_define("idx-i2fill", &K_idx_i2fill_Rae619e91052f170f); 
 dh_define("idx-i1fill-with-index", &K_idx_i1fill_with_index_R76cd27893fba9ae5); 
 dh_define("random-permute", &K_random_permute_R76cd27893fba9ae5); 
 dh_define("fast-multinomial-sample", &K_fast_multinomial_sample_Ra6981d6c310d95e3); 
 dh_define("multinomial-sample", &K_multinomial_sample_Ra6981d6c310d95e3); 
 dh_define("distribution2cumulative", &K_distribution2cumulative_R1df63318569a8a7a); 
 dh_define("element-in-set", &K_element_in_set_Rf5fa1be8cd48ba32); 
}

int majver_idx_int = 40;
int minver_idx_int = 10;


#endif

