/* WARNING: Automatically generated code.
 * This code has been generated by the DH compiler.
 */
#ifdef HAVE_CONFIG_H
# include "lushconf.h"
#endif

/*
 * LUSH HEADERS
 */
#include "header.h"
#include "dh.h"
#include "idxmac.h"
#include "idxops.h"
#include "check_func.h"



/* ---------------------------------------- */


/*
 * FUNCTION idx-f1resize
 */
extern_c char C_idx_f1resize(struct idx* L1_m,intg L1_n0)
{
TRACE_PUSH("C_idx_f1resize");
{
Midx_init_dim1(L1_m,L1_n0);
TRACE_POP("C_idx_f1resize");
return 0;
}
}

/*
 * FUNCTION idx-f2resize
 */
extern_c char C_idx_f2resize(struct idx* L1_m,intg L1_n0,intg L1_n1)
{
TRACE_PUSH("C_idx_f2resize");
{
Midx_init_dim2(L1_m,L1_n0,L1_n1);
TRACE_POP("C_idx_f2resize");
return 0;
}
}

/*
 * FUNCTION idx-f3resize
 */
extern_c char C_idx_f3resize(struct idx* L1_m,intg L1_n0,intg L1_n1,intg L1_n2)
{
TRACE_PUSH("C_idx_f3resize");
{
Midx_init_dim3(L1_m,L1_n0,L1_n1,L1_n2);
TRACE_POP("C_idx_f3resize");
return 0;
}
}

/*
 * FUNCTION idx-f4resize
 */
extern_c char C_idx_f4resize(struct idx* L1_m,intg L1_n0,intg L1_n1,intg L1_n2,intg L1_n3)
{
TRACE_PUSH("C_idx_f4resize");
{
Midx_init_dim4(L1_m,L1_n0,L1_n1,L1_n2,L1_n3);
TRACE_POP("C_idx_f4resize");
return 0;
}
}

/*
 * FUNCTION idx-i1resize
 */
extern_c char C_idx_i1resize(struct idx* L1_m,intg L1_n0)
{
TRACE_PUSH("C_idx_i1resize");
{
Midx_init_dim1(L1_m,L1_n0);
TRACE_POP("C_idx_i1resize");
return 0;
}
}

/*
 * FUNCTION idx-i2resize
 */
extern_c char C_idx_i2resize(struct idx* L1_m,intg L1_n0,intg L1_n1)
{
TRACE_PUSH("C_idx_i2resize");
{
Midx_init_dim2(L1_m,L1_n0,L1_n1);
TRACE_POP("C_idx_i2resize");
return 0;
}
}

/*
 * FUNCTION idx-i3resize
 */
extern_c char C_idx_i3resize(struct idx* L1_m,intg L1_n0,intg L1_n1,intg L1_n2)
{
TRACE_PUSH("C_idx_i3resize");
{
Midx_init_dim3(L1_m,L1_n0,L1_n1,L1_n2);
TRACE_POP("C_idx_i3resize");
return 0;
}
}

/*
 * FUNCTION idx-i4resize
 */
extern_c char C_idx_i4resize(struct idx* L1_m,intg L1_n0,intg L1_n1,intg L1_n2,intg L1_n3)
{
TRACE_PUSH("C_idx_i4resize");
{
Midx_init_dim4(L1_m,L1_n0,L1_n1,L1_n2,L1_n3);
TRACE_POP("C_idx_i4resize");
return 0;
}
}

/*
 * FUNCTION idx-s1resize
 */
extern_c char C_idx_s1resize(struct idx* L1_m,intg L1_n0)
{
TRACE_PUSH("C_idx_s1resize");
{
Midx_init_dim1(L1_m,L1_n0);
TRACE_POP("C_idx_s1resize");
return 0;
}
}

/*
 * FUNCTION idx-s2resize
 */
extern_c char C_idx_s2resize(struct idx* L1_m,intg L1_n0,intg L1_n1)
{
TRACE_PUSH("C_idx_s2resize");
{
Midx_init_dim2(L1_m,L1_n0,L1_n1);
TRACE_POP("C_idx_s2resize");
return 0;
}
}

/*
 * FUNCTION idx-s3resize
 */
extern_c char C_idx_s3resize(struct idx* L1_m,intg L1_n0,intg L1_n1,intg L1_n2)
{
TRACE_PUSH("C_idx_s3resize");
{
Midx_init_dim3(L1_m,L1_n0,L1_n1,L1_n2);
TRACE_POP("C_idx_s3resize");
return 0;
}
}

/*
 * FUNCTION idx-s4resize
 */
extern_c char C_idx_s4resize(struct idx* L1_m,intg L1_n0,intg L1_n1,intg L1_n2,intg L1_n3)
{
TRACE_PUSH("C_idx_s4resize");
{
Midx_init_dim4(L1_m,L1_n0,L1_n1,L1_n2,L1_n3);
TRACE_POP("C_idx_s4resize");
return 0;
}
}

/*
 * FUNCTION idx-b1resize
 */
extern_c char C_idx_b1resize(struct idx* L1_m,intg L1_n0)
{
TRACE_PUSH("C_idx_b1resize");
{
Midx_init_dim1(L1_m,L1_n0);
TRACE_POP("C_idx_b1resize");
return 0;
}
}

/*
 * FUNCTION idx-b2resize
 */
extern_c char C_idx_b2resize(struct idx* L1_m,intg L1_n0,intg L1_n1)
{
TRACE_PUSH("C_idx_b2resize");
{
Midx_init_dim2(L1_m,L1_n0,L1_n1);
TRACE_POP("C_idx_b2resize");
return 0;
}
}

/*
 * FUNCTION idx-b3resize
 */
extern_c char C_idx_b3resize(struct idx* L1_m,intg L1_n0,intg L1_n1,intg L1_n2)
{
TRACE_PUSH("C_idx_b3resize");
{
Midx_init_dim3(L1_m,L1_n0,L1_n1,L1_n2);
TRACE_POP("C_idx_b3resize");
return 0;
}
}

/*
 * FUNCTION idx-b4resize
 */
extern_c char C_idx_b4resize(struct idx* L1_m,intg L1_n0,intg L1_n1,intg L1_n2,intg L1_n3)
{
TRACE_PUSH("C_idx_b4resize");
{
Midx_init_dim4(L1_m,L1_n0,L1_n1,L1_n2,L1_n3);
TRACE_POP("C_idx_b4resize");
return 0;
}
}

/*
 * FUNCTION idx-u1resize
 */
extern_c char C_idx_u1resize(struct idx* L1_m,intg L1_n0)
{
TRACE_PUSH("C_idx_u1resize");
{
Midx_init_dim1(L1_m,L1_n0);
TRACE_POP("C_idx_u1resize");
return 0;
}
}

/*
 * FUNCTION idx-u2resize
 */
extern_c char C_idx_u2resize(struct idx* L1_m,intg L1_n0,intg L1_n1)
{
TRACE_PUSH("C_idx_u2resize");
{
Midx_init_dim2(L1_m,L1_n0,L1_n1);
TRACE_POP("C_idx_u2resize");
return 0;
}
}

/*
 * FUNCTION idx-u3resize
 */
extern_c char C_idx_u3resize(struct idx* L1_m,intg L1_n0,intg L1_n1,intg L1_n2)
{
TRACE_PUSH("C_idx_u3resize");
{
Midx_init_dim3(L1_m,L1_n0,L1_n1,L1_n2);
TRACE_POP("C_idx_u3resize");
return 0;
}
}

/*
 * FUNCTION idx-u4resize
 */
extern_c char C_idx_u4resize(struct idx* L1_m,intg L1_n0,intg L1_n1,intg L1_n2,intg L1_n3)
{
TRACE_PUSH("C_idx_u4resize");
{
Midx_init_dim4(L1_m,L1_n0,L1_n1,L1_n2,L1_n3);
TRACE_POP("C_idx_u4resize");
return 0;
}
}

/*
 * FUNCTION idx-g1resize
 */
extern_c char C_idx_g1resize(struct idx* L1_m,intg L1_n0)
{
TRACE_PUSH("C_idx_g1resize");
{
Midx_init_dim1(L1_m,L1_n0);
TRACE_POP("C_idx_g1resize");
return 0;
}
}

/*
 * FUNCTION idx-g2resize
 */
extern_c char C_idx_g2resize(struct idx* L1_m,intg L1_n0,intg L1_n1)
{
TRACE_PUSH("C_idx_g2resize");
{
Midx_init_dim2(L1_m,L1_n0,L1_n1);
TRACE_POP("C_idx_g2resize");
return 0;
}
}

/*
 * FUNCTION idx-g3resize
 */
extern_c char C_idx_g3resize(struct idx* L1_m,intg L1_n0,intg L1_n1,intg L1_n2)
{
TRACE_PUSH("C_idx_g3resize");
{
Midx_init_dim3(L1_m,L1_n0,L1_n1,L1_n2);
TRACE_POP("C_idx_g3resize");
return 0;
}
}

/*
 * FUNCTION idx-g4resize
 */
extern_c char C_idx_g4resize(struct idx* L1_m,intg L1_n0,intg L1_n1,intg L1_n2,intg L1_n3)
{
TRACE_PUSH("C_idx_g4resize");
{
Midx_init_dim4(L1_m,L1_n0,L1_n1,L1_n2,L1_n3);
TRACE_POP("C_idx_g4resize");
return 0;
}
}

/*
 * FUNCTION idx-d1resize
 */
extern_c char C_idx_d1resize(struct idx* L1_m,intg L1_n0)
{
TRACE_PUSH("C_idx_d1resize");
{
Midx_init_dim1(L1_m,L1_n0);
TRACE_POP("C_idx_d1resize");
return 0;
}
}

/*
 * FUNCTION idx-d2resize
 */
extern_c char C_idx_d2resize(struct idx* L1_m,intg L1_n0,intg L1_n1)
{
TRACE_PUSH("C_idx_d2resize");
{
Midx_init_dim2(L1_m,L1_n0,L1_n1);
TRACE_POP("C_idx_d2resize");
return 0;
}
}

/*
 * FUNCTION idx-d3resize
 */
extern_c char C_idx_d3resize(struct idx* L1_m,intg L1_n0,intg L1_n1,intg L1_n2)
{
TRACE_PUSH("C_idx_d3resize");
{
Midx_init_dim3(L1_m,L1_n0,L1_n1,L1_n2);
TRACE_POP("C_idx_d3resize");
return 0;
}
}

/*
 * FUNCTION idx-d4resize
 */
extern_c char C_idx_d4resize(struct idx* L1_m,intg L1_n0,intg L1_n1,intg L1_n2,intg L1_n3)
{
TRACE_PUSH("C_idx_d4resize");
{
Midx_init_dim4(L1_m,L1_n0,L1_n1,L1_n2,L1_n3);
TRACE_POP("C_idx_d4resize");
return 0;
}
}

/* ---------------------------------------- */

#ifndef NOLISP


/*
 * STUB idx-f1resize
 */
DH(X_idx_f1resize)
{
dharg ret;
ret.dh_char =  C_idx_f1resize(a[1].dh_idx_ptr, a[2].dh_int);
return ret;
}

/*
 * DHDOC idx-f1resize
 */
DHDOC(K_idx_f1resize_R02dfaa504835134e,X_idx_f1resize,"C_idx_f1resize",0,0) = {
DH_FUNC(2),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_FLT,
DH_INT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-f2resize
 */
DH(X_idx_f2resize)
{
dharg ret;
ret.dh_char =  C_idx_f2resize(a[1].dh_idx_ptr, a[2].dh_int, a[3].dh_int);
return ret;
}

/*
 * DHDOC idx-f2resize
 */
DHDOC(K_idx_f2resize_R46448523ea300459,X_idx_f2resize,"C_idx_f2resize",0,0) = {
DH_FUNC(3),
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_FLT,
DH_INT,
DH_INT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-f3resize
 */
DH(X_idx_f3resize)
{
dharg ret;
ret.dh_char =  C_idx_f3resize(a[1].dh_idx_ptr, a[2].dh_int, a[3].dh_int, a[4].dh_int);
return ret;
}

/*
 * DHDOC idx-f3resize
 */
DHDOC(K_idx_f3resize_Rcf72dbc4ae3a2a77,X_idx_f3resize,"C_idx_f3resize",0,0) = {
DH_FUNC(4),
DH_IDX(DHT_READ,3),
DH_SRG(DHT_READ),
DH_FLT,
DH_INT,
DH_INT,
DH_INT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-f4resize
 */
DH(X_idx_f4resize)
{
dharg ret;
ret.dh_char =  C_idx_f4resize(a[1].dh_idx_ptr, a[2].dh_int, a[3].dh_int, a[4].dh_int, a[5].dh_int);
return ret;
}

/*
 * DHDOC idx-f4resize
 */
DHDOC(K_idx_f4resize_Rdd1e660a262e762a,X_idx_f4resize,"C_idx_f4resize",0,0) = {
DH_FUNC(5),
DH_IDX(DHT_READ,4),
DH_SRG(DHT_READ),
DH_FLT,
DH_INT,
DH_INT,
DH_INT,
DH_INT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-i1resize
 */
DH(X_idx_i1resize)
{
dharg ret;
ret.dh_char =  C_idx_i1resize(a[1].dh_idx_ptr, a[2].dh_int);
return ret;
}

/*
 * DHDOC idx-i1resize
 */
DHDOC(K_idx_i1resize_Rae619e91052f170f,X_idx_i1resize,"C_idx_i1resize",0,0) = {
DH_FUNC(2),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_INT,
DH_INT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-i2resize
 */
DH(X_idx_i2resize)
{
dharg ret;
ret.dh_char =  C_idx_i2resize(a[1].dh_idx_ptr, a[2].dh_int, a[3].dh_int);
return ret;
}

/*
 * DHDOC idx-i2resize
 */
DHDOC(K_idx_i2resize_R1f38eca170040cda,X_idx_i2resize,"C_idx_i2resize",0,0) = {
DH_FUNC(3),
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_INT,
DH_INT,
DH_INT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-i3resize
 */
DH(X_idx_i3resize)
{
dharg ret;
ret.dh_char =  C_idx_i3resize(a[1].dh_idx_ptr, a[2].dh_int, a[3].dh_int, a[4].dh_int);
return ret;
}

/*
 * DHDOC idx-i3resize
 */
DHDOC(K_idx_i3resize_R7d8a08c19a523b71,X_idx_i3resize,"C_idx_i3resize",0,0) = {
DH_FUNC(4),
DH_IDX(DHT_READ,3),
DH_SRG(DHT_READ),
DH_INT,
DH_INT,
DH_INT,
DH_INT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-i4resize
 */
DH(X_idx_i4resize)
{
dharg ret;
ret.dh_char =  C_idx_i4resize(a[1].dh_idx_ptr, a[2].dh_int, a[3].dh_int, a[4].dh_int, a[5].dh_int);
return ret;
}

/*
 * DHDOC idx-i4resize
 */
DHDOC(K_idx_i4resize_Rb8efc0004efe5427,X_idx_i4resize,"C_idx_i4resize",0,0) = {
DH_FUNC(5),
DH_IDX(DHT_READ,4),
DH_SRG(DHT_READ),
DH_INT,
DH_INT,
DH_INT,
DH_INT,
DH_INT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-s1resize
 */
DH(X_idx_s1resize)
{
dharg ret;
ret.dh_char =  C_idx_s1resize(a[1].dh_idx_ptr, a[2].dh_int);
return ret;
}

/*
 * DHDOC idx-s1resize
 */
DHDOC(K_idx_s1resize_Ra8c3d1dacb07e2a4,X_idx_s1resize,"C_idx_s1resize",0,0) = {
DH_FUNC(2),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_SHORT,
DH_INT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-s2resize
 */
DH(X_idx_s2resize)
{
dharg ret;
ret.dh_char =  C_idx_s2resize(a[1].dh_idx_ptr, a[2].dh_int, a[3].dh_int);
return ret;
}

/*
 * DHDOC idx-s2resize
 */
DHDOC(K_idx_s2resize_R127c7236ec55e78c,X_idx_s2resize,"C_idx_s2resize",0,0) = {
DH_FUNC(3),
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_SHORT,
DH_INT,
DH_INT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-s3resize
 */
DH(X_idx_s3resize)
{
dharg ret;
ret.dh_char =  C_idx_s3resize(a[1].dh_idx_ptr, a[2].dh_int, a[3].dh_int, a[4].dh_int);
return ret;
}

/*
 * DHDOC idx-s3resize
 */
DHDOC(K_idx_s3resize_R670335eea2f1eddd,X_idx_s3resize,"C_idx_s3resize",0,0) = {
DH_FUNC(4),
DH_IDX(DHT_READ,3),
DH_SRG(DHT_READ),
DH_SHORT,
DH_INT,
DH_INT,
DH_INT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-s4resize
 */
DH(X_idx_s4resize)
{
dharg ret;
ret.dh_char =  C_idx_s4resize(a[1].dh_idx_ptr, a[2].dh_int, a[3].dh_int, a[4].dh_int, a[5].dh_int);
return ret;
}

/*
 * DHDOC idx-s4resize
 */
DHDOC(K_idx_s4resize_R8dfdba5e3fb9f97f,X_idx_s4resize,"C_idx_s4resize",0,0) = {
DH_FUNC(5),
DH_IDX(DHT_READ,4),
DH_SRG(DHT_READ),
DH_SHORT,
DH_INT,
DH_INT,
DH_INT,
DH_INT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-b1resize
 */
DH(X_idx_b1resize)
{
dharg ret;
ret.dh_char =  C_idx_b1resize(a[1].dh_idx_ptr, a[2].dh_int);
return ret;
}

/*
 * DHDOC idx-b1resize
 */
DHDOC(K_idx_b1resize_R0e551cc7ec1135c3,X_idx_b1resize,"C_idx_b1resize",0,0) = {
DH_FUNC(2),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_BYTE,
DH_INT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-b2resize
 */
DH(X_idx_b2resize)
{
dharg ret;
ret.dh_char =  C_idx_b2resize(a[1].dh_idx_ptr, a[2].dh_int, a[3].dh_int);
return ret;
}

/*
 * DHDOC idx-b2resize
 */
DHDOC(K_idx_b2resize_R5f51e80ca2784943,X_idx_b2resize,"C_idx_b2resize",0,0) = {
DH_FUNC(3),
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_BYTE,
DH_INT,
DH_INT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-b3resize
 */
DH(X_idx_b3resize)
{
dharg ret;
ret.dh_char =  C_idx_b3resize(a[1].dh_idx_ptr, a[2].dh_int, a[3].dh_int, a[4].dh_int);
return ret;
}

/*
 * DHDOC idx-b3resize
 */
DHDOC(K_idx_b3resize_Rfd58019a3eaab043,X_idx_b3resize,"C_idx_b3resize",0,0) = {
DH_FUNC(4),
DH_IDX(DHT_READ,3),
DH_SRG(DHT_READ),
DH_BYTE,
DH_INT,
DH_INT,
DH_INT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-b4resize
 */
DH(X_idx_b4resize)
{
dharg ret;
ret.dh_char =  C_idx_b4resize(a[1].dh_idx_ptr, a[2].dh_int, a[3].dh_int, a[4].dh_int, a[5].dh_int);
return ret;
}

/*
 * DHDOC idx-b4resize
 */
DHDOC(K_idx_b4resize_Rb94bd2b7070f4242,X_idx_b4resize,"C_idx_b4resize",0,0) = {
DH_FUNC(5),
DH_IDX(DHT_READ,4),
DH_SRG(DHT_READ),
DH_BYTE,
DH_INT,
DH_INT,
DH_INT,
DH_INT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-u1resize
 */
DH(X_idx_u1resize)
{
dharg ret;
ret.dh_char =  C_idx_u1resize(a[1].dh_idx_ptr, a[2].dh_int);
return ret;
}

/*
 * DHDOC idx-u1resize
 */
DHDOC(K_idx_u1resize_R86d55eddc5b5d5e1,X_idx_u1resize,"C_idx_u1resize",0,0) = {
DH_FUNC(2),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_UBYTE,
DH_INT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-u2resize
 */
DH(X_idx_u2resize)
{
dharg ret;
ret.dh_char =  C_idx_u2resize(a[1].dh_idx_ptr, a[2].dh_int, a[3].dh_int);
return ret;
}

/*
 * DHDOC idx-u2resize
 */
DHDOC(K_idx_u2resize_R4e516c38f1318906,X_idx_u2resize,"C_idx_u2resize",0,0) = {
DH_FUNC(3),
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_UBYTE,
DH_INT,
DH_INT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-u3resize
 */
DH(X_idx_u3resize)
{
dharg ret;
ret.dh_char =  C_idx_u3resize(a[1].dh_idx_ptr, a[2].dh_int, a[3].dh_int, a[4].dh_int);
return ret;
}

/*
 * DHDOC idx-u3resize
 */
DHDOC(K_idx_u3resize_Rdf5909f2983930c9,X_idx_u3resize,"C_idx_u3resize",0,0) = {
DH_FUNC(4),
DH_IDX(DHT_READ,3),
DH_SRG(DHT_READ),
DH_UBYTE,
DH_INT,
DH_INT,
DH_INT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-u4resize
 */
DH(X_idx_u4resize)
{
dharg ret;
ret.dh_char =  C_idx_u4resize(a[1].dh_idx_ptr, a[2].dh_int, a[3].dh_int, a[4].dh_int, a[5].dh_int);
return ret;
}

/*
 * DHDOC idx-u4resize
 */
DHDOC(K_idx_u4resize_Rfd49c2664a284356,X_idx_u4resize,"C_idx_u4resize",0,0) = {
DH_FUNC(5),
DH_IDX(DHT_READ,4),
DH_SRG(DHT_READ),
DH_UBYTE,
DH_INT,
DH_INT,
DH_INT,
DH_INT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-g1resize
 */
DH(X_idx_g1resize)
{
dharg ret;
ret.dh_char =  C_idx_g1resize(a[1].dh_idx_ptr, a[2].dh_int);
return ret;
}

/*
 * DHDOC idx-g1resize
 */
DHDOC(K_idx_g1resize_R800918c2414f3bcc,X_idx_g1resize,"C_idx_g1resize",0,0) = {
DH_FUNC(2),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_GPTR(0),
DH_INT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-g2resize
 */
DH(X_idx_g2resize)
{
dharg ret;
ret.dh_char =  C_idx_g2resize(a[1].dh_idx_ptr, a[2].dh_int, a[3].dh_int);
return ret;
}

/*
 * DHDOC idx-g2resize
 */
DHDOC(K_idx_g2resize_R43e9e007f8c4555c,X_idx_g2resize,"C_idx_g2resize",0,0) = {
DH_FUNC(3),
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_GPTR(0),
DH_INT,
DH_INT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-g3resize
 */
DH(X_idx_g3resize)
{
dharg ret;
ret.dh_char =  C_idx_g3resize(a[1].dh_idx_ptr, a[2].dh_int, a[3].dh_int, a[4].dh_int);
return ret;
}

/*
 * DHDOC idx-g3resize
 */
DHDOC(K_idx_g3resize_Rc428118c8bd2887d,X_idx_g3resize,"C_idx_g3resize",0,0) = {
DH_FUNC(4),
DH_IDX(DHT_READ,3),
DH_SRG(DHT_READ),
DH_GPTR(0),
DH_INT,
DH_INT,
DH_INT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-g4resize
 */
DH(X_idx_g4resize)
{
dharg ret;
ret.dh_char =  C_idx_g4resize(a[1].dh_idx_ptr, a[2].dh_int, a[3].dh_int, a[4].dh_int, a[5].dh_int);
return ret;
}

/*
 * DHDOC idx-g4resize
 */
DHDOC(K_idx_g4resize_Rcbabf29a6dff323e,X_idx_g4resize,"C_idx_g4resize",0,0) = {
DH_FUNC(5),
DH_IDX(DHT_READ,4),
DH_SRG(DHT_READ),
DH_GPTR(0),
DH_INT,
DH_INT,
DH_INT,
DH_INT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d1resize
 */
DH(X_idx_d1resize)
{
dharg ret;
ret.dh_char =  C_idx_d1resize(a[1].dh_idx_ptr, a[2].dh_int);
return ret;
}

/*
 * DHDOC idx-d1resize
 */
DHDOC(K_idx_d1resize_R2eeeb5742a8a9c80,X_idx_d1resize,"C_idx_d1resize",0,0) = {
DH_FUNC(2),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_INT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d2resize
 */
DH(X_idx_d2resize)
{
dharg ret;
ret.dh_char =  C_idx_d2resize(a[1].dh_idx_ptr, a[2].dh_int, a[3].dh_int);
return ret;
}

/*
 * DHDOC idx-d2resize
 */
DHDOC(K_idx_d2resize_R1e26bb6b2f4f1bc5,X_idx_d2resize,"C_idx_d2resize",0,0) = {
DH_FUNC(3),
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_REAL,
DH_INT,
DH_INT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d3resize
 */
DH(X_idx_d3resize)
{
dharg ret;
ret.dh_char =  C_idx_d3resize(a[1].dh_idx_ptr, a[2].dh_int, a[3].dh_int, a[4].dh_int);
return ret;
}

/*
 * DHDOC idx-d3resize
 */
DHDOC(K_idx_d3resize_R7fb6a75524c4154f,X_idx_d3resize,"C_idx_d3resize",0,0) = {
DH_FUNC(4),
DH_IDX(DHT_READ,3),
DH_SRG(DHT_READ),
DH_REAL,
DH_INT,
DH_INT,
DH_INT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB idx-d4resize
 */
DH(X_idx_d4resize)
{
dharg ret;
ret.dh_char =  C_idx_d4resize(a[1].dh_idx_ptr, a[2].dh_int, a[3].dh_int, a[4].dh_int, a[5].dh_int);
return ret;
}

/*
 * DHDOC idx-d4resize
 */
DHDOC(K_idx_d4resize_Rbc969f2933d2085b,X_idx_d4resize,"C_idx_d4resize",0,0) = {
DH_FUNC(5),
DH_IDX(DHT_READ,4),
DH_SRG(DHT_READ),
DH_REAL,
DH_INT,
DH_INT,
DH_INT,
DH_INT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * INIT FUNCTION
 */
extern_c void init_idx_macros(void)
{
 dh_define("idx-f1resize", &K_idx_f1resize_R02dfaa504835134e); 
 dh_define("idx-f2resize", &K_idx_f2resize_R46448523ea300459); 
 dh_define("idx-f3resize", &K_idx_f3resize_Rcf72dbc4ae3a2a77); 
 dh_define("idx-f4resize", &K_idx_f4resize_Rdd1e660a262e762a); 
 dh_define("idx-i1resize", &K_idx_i1resize_Rae619e91052f170f); 
 dh_define("idx-i2resize", &K_idx_i2resize_R1f38eca170040cda); 
 dh_define("idx-i3resize", &K_idx_i3resize_R7d8a08c19a523b71); 
 dh_define("idx-i4resize", &K_idx_i4resize_Rb8efc0004efe5427); 
 dh_define("idx-s1resize", &K_idx_s1resize_Ra8c3d1dacb07e2a4); 
 dh_define("idx-s2resize", &K_idx_s2resize_R127c7236ec55e78c); 
 dh_define("idx-s3resize", &K_idx_s3resize_R670335eea2f1eddd); 
 dh_define("idx-s4resize", &K_idx_s4resize_R8dfdba5e3fb9f97f); 
 dh_define("idx-b1resize", &K_idx_b1resize_R0e551cc7ec1135c3); 
 dh_define("idx-b2resize", &K_idx_b2resize_R5f51e80ca2784943); 
 dh_define("idx-b3resize", &K_idx_b3resize_Rfd58019a3eaab043); 
 dh_define("idx-b4resize", &K_idx_b4resize_Rb94bd2b7070f4242); 
 dh_define("idx-u1resize", &K_idx_u1resize_R86d55eddc5b5d5e1); 
 dh_define("idx-u2resize", &K_idx_u2resize_R4e516c38f1318906); 
 dh_define("idx-u3resize", &K_idx_u3resize_Rdf5909f2983930c9); 
 dh_define("idx-u4resize", &K_idx_u4resize_Rfd49c2664a284356); 
 dh_define("idx-g1resize", &K_idx_g1resize_R800918c2414f3bcc); 
 dh_define("idx-g2resize", &K_idx_g2resize_R43e9e007f8c4555c); 
 dh_define("idx-g3resize", &K_idx_g3resize_Rc428118c8bd2887d); 
 dh_define("idx-g4resize", &K_idx_g4resize_Rcbabf29a6dff323e); 
 dh_define("idx-d1resize", &K_idx_d1resize_R2eeeb5742a8a9c80); 
 dh_define("idx-d2resize", &K_idx_d2resize_R1e26bb6b2f4f1bc5); 
 dh_define("idx-d3resize", &K_idx_d3resize_R7fb6a75524c4154f); 
 dh_define("idx-d4resize", &K_idx_d4resize_Rbc969f2933d2085b); 
}

int majver_idx_macros = 40;
int minver_idx_macros = 10;


#endif

