/* WARNING: Automatically generated code.
 * This code has been generated by the DH compiler.
 */
#ifdef HAVE_CONFIG_H
# include "lushconf.h"
#endif

/*
 * USER DEFINED HEADERS
 */
 #include "mapper-c.h"
/*
 * LUSH HEADERS
 */
#include "header.h"
#include "dh.h"
#include "idxmac.h"
#include "idxops.h"
#include "check_func.h"



/* ---------------------------------------- */


/*
 * FUNCTION _mapper-slink-inner
 */
extern_c intg C__mapper_slink_inner(struct idx* L1_data,struct srg* L1_metric,struct idx* L1_ml,struct idx* L1_mr,struct idx* L1_md)
{
TRACE_PUSH("C__mapper_slink_inner");
{
intg L_Tmp0;
{
intg L2_1_n;
intg L2_2_nc;
intg L2_3_rc;
L2_1_n = (L1_data)->dim[0];
L2_2_nc = (L1_data)->dim[1];
L2_3_rc = 0;
{
       if ((L1_data)->mod[1] != 1)
         error(NIL, "data must be contiguous (mod[1]=1)", NIL);
       metric_fn_t mf = mapper_select_metric((L1_metric)->data);
       if (!mf) error(NIL, "unknown metric", new_string((L1_metric)->data));
       (L2_3_rc) = mapper_slink_data(IDX_PTR((L1_data), double), (L2_1_n), (L2_2_nc), mf,
                               IDX_PTR((L1_ml), int), IDX_PTR((L1_mr), int),
                               IDX_PTR((L1_md), double));
    }
L_Tmp0 = L2_3_rc;
}
TRACE_POP("C__mapper_slink_inner");
return L_Tmp0;
}
}

/*
 * FUNCTION _mapper-slink-dm-inner
 */
extern_c intg C__mapper_slink_dm_inner(struct idx* L1_dm,intg L1_n,struct idx* L1_ml,struct idx* L1_mr,struct idx* L1_md)
{
TRACE_PUSH("C__mapper_slink_dm_inner");
{
intg L_Tmp0;
{
intg L2_1_rc;
L2_1_rc = 0;
{
       (L2_1_rc) = mapper_slink(IDX_PTR((L1_dm), double), (L1_n),
                          IDX_PTR((L1_ml), int), IDX_PTR((L1_mr), int),
                          IDX_PTR((L1_md), double));
    }
L_Tmp0 = L2_1_rc;
}
TRACE_POP("C__mapper_slink_dm_inner");
return L_Tmp0;
}
}

/*
 * FUNCTION _mapper-cut-tree-inner
 */
extern_c char C__mapper_cut_tree_inner(intg L1_nelements,struct idx* L1_ml,struct idx* L1_mr,struct idx* L1_md,intg L1_nclusters,struct idx* L1_labels)
{
TRACE_PUSH("C__mapper_cut_tree_inner");
{
char L_Tmp0;
{
     mapper_cut_tree((L1_nelements),
                     IDX_PTR((L1_ml), int), IDX_PTR((L1_mr), int),
                     IDX_PTR((L1_md), double),
                     (L1_nclusters), IDX_PTR((L1_labels), int));
  }
L_Tmp0 = 1;
TRACE_POP("C__mapper_cut_tree_inner");
return L_Tmp0;
}
}

/*
 * FUNCTION _mapper-cut-tree-dist-inner
 */
extern_c intg C__mapper_cut_tree_dist_inner(intg L1_nelements,struct idx* L1_ml,struct idx* L1_mr,struct idx* L1_md,real L1_threshold,struct idx* L1_labels)
{
TRACE_PUSH("C__mapper_cut_tree_dist_inner");
{
intg L_Tmp0;
{
intg L2_1_nc;
L2_1_nc = 0;
{
       (L2_1_nc) = mapper_cut_tree_dist((L1_nelements),
                                  IDX_PTR((L1_ml), int), IDX_PTR((L1_mr), int),
                                  IDX_PTR((L1_md), double),
                                  (L1_threshold), IDX_PTR((L1_labels), int));
    }
L_Tmp0 = L2_1_nc;
}
TRACE_POP("C__mapper_cut_tree_dist_inner");
return L_Tmp0;
}
}

/*
 * FUNCTION _mapper-dbscan-inner
 */
extern_c intg C__mapper_dbscan_inner(struct idx* L1_data,real L1_eps,intg L1_min_pts,struct srg* L1_metric,struct idx* L1_labels)
{
TRACE_PUSH("C__mapper_dbscan_inner");
{
intg L_Tmp0;
{
intg L2_1_n;
intg L2_2_nc;
intg L2_3_ncl;
L2_1_n = (L1_data)->dim[0];
L2_2_nc = (L1_data)->dim[1];
L2_3_ncl = 0;
{
       if ((L1_data)->mod[1] != 1)
         error(NIL, "data must be contiguous (mod[1]=1)", NIL);
       const char *mname = (L1_metric)->data;
       if (!strcmp(mname, "euclidean")) {
         (L2_3_ncl) = mapper_dbscan_kdtree(IDX_PTR((L1_data), double), (L2_1_n), (L2_2_nc),
                                     (L1_eps), (L1_min_pts), IDX_PTR((L1_labels), int));
       } else {
         metric_fn_t mf = mapper_select_metric(mname);
         if (!mf) error(NIL, "unknown metric", new_string((L1_metric)->data));
         (L2_3_ncl) = mapper_dbscan_data(IDX_PTR((L1_data), double), (L2_1_n), (L2_2_nc), mf,
                                   (L1_eps), (L1_min_pts), IDX_PTR((L1_labels), int));
       }
    }
L_Tmp0 = L2_3_ncl;
}
TRACE_POP("C__mapper_dbscan_inner");
return L_Tmp0;
}
}

/*
 * FUNCTION _mapper-dbscan-dm-inner
 */
extern_c intg C__mapper_dbscan_dm_inner(struct idx* L1_dm,intg L1_n,real L1_eps,intg L1_min_pts,struct idx* L1_labels)
{
TRACE_PUSH("C__mapper_dbscan_dm_inner");
{
intg L_Tmp0;
{
intg L2_1_ncl;
L2_1_ncl = 0;
{
       (L2_1_ncl) = mapper_dbscan(IDX_PTR((L1_dm), double), (L1_n), (L1_eps), (L1_min_pts),
                            IDX_PTR((L1_labels), int));
    }
L_Tmp0 = L2_1_ncl;
}
TRACE_POP("C__mapper_dbscan_dm_inner");
return L_Tmp0;
}
}

/*
 * FUNCTION mapper-isect-count
 */
extern_c intg C_mapper_isect_count(struct idx* L1_a,struct idx* L1_b)
{
TRACE_PUSH("C_mapper_isect_count");
{
intg L_Tmp0;
{
intg L2_1_na;
intg L2_2_nb;
intg L2_3_c;
L2_1_na = (L1_a)->dim[0];
L2_2_nb = (L1_b)->dim[0];
L2_3_c = 0;
{
       (L2_3_c) = mapper_sorted_isect_count(IDX_PTR((L1_a), int), (L2_1_na),
                                      IDX_PTR((L1_b), int), (L2_2_nb));
    }
L_Tmp0 = L2_3_c;
}
TRACE_POP("C_mapper_isect_count");
return L_Tmp0;
}
}

/* ---------------------------------------- */

#ifndef NOLISP


/*
 * STUB _mapper-slink-inner
 */
DH(X__mapper_slink_inner)
{
dharg ret;
ret.dh_int =  C__mapper_slink_inner(a[1].dh_idx_ptr, a[2].dh_srg_ptr, a[3].dh_idx_ptr, a[4].dh_idx_ptr, a[5].dh_idx_ptr);
return ret;
}

/*
 * DHDOC _mapper-slink-inner
 */
DHDOC(K__mapper_slink_inner_Rc7d1a7b1ef9e6368,X__mapper_slink_inner,"C__mapper_slink_inner",0,0) = {
DH_FUNC(5),
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_REAL,
DH_STR,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_INT,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_INT,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_RETURN,
DH_INT,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB _mapper-slink-dm-inner
 */
DH(X__mapper_slink_dm_inner)
{
dharg ret;
ret.dh_int =  C__mapper_slink_dm_inner(a[1].dh_idx_ptr, a[2].dh_int, a[3].dh_idx_ptr, a[4].dh_idx_ptr, a[5].dh_idx_ptr);
return ret;
}

/*
 * DHDOC _mapper-slink-dm-inner
 */
DHDOC(K__mapper_slink_dm_inner_R049aa38524d701d4,X__mapper_slink_dm_inner,"C__mapper_slink_dm_inner",0,0) = {
DH_FUNC(5),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_INT,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_INT,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_INT,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_RETURN,
DH_INT,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB _mapper-cut-tree-inner
 */
DH(X__mapper_cut_tree_inner)
{
dharg ret;
ret.dh_char =  C__mapper_cut_tree_inner(a[1].dh_int, a[2].dh_idx_ptr, a[3].dh_idx_ptr, a[4].dh_idx_ptr, a[5].dh_int, a[6].dh_idx_ptr);
return ret;
}

/*
 * DHDOC _mapper-cut-tree-inner
 */
DHDOC(K__mapper_cut_tree_inner_R2d9ac71aa72b61a1,X__mapper_cut_tree_inner,"C__mapper_cut_tree_inner",0,0) = {
DH_FUNC(6),
DH_INT,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_INT,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_INT,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_INT,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_INT,
DH_RETURN,
DH_BOOL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB _mapper-cut-tree-dist-inner
 */
DH(X__mapper_cut_tree_dist_inner)
{
dharg ret;
ret.dh_int =  C__mapper_cut_tree_dist_inner(a[1].dh_int, a[2].dh_idx_ptr, a[3].dh_idx_ptr, a[4].dh_idx_ptr, a[5].dh_real, a[6].dh_idx_ptr);
return ret;
}

/*
 * DHDOC _mapper-cut-tree-dist-inner
 */
DHDOC(K__mapper_cut_tree_dist_inner_R4b32ed1da585fc27,X__mapper_cut_tree_dist_inner,"C__mapper_cut_tree_dist_inner",0,0) = {
DH_FUNC(6),
DH_INT,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_INT,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_INT,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_REAL,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_INT,
DH_RETURN,
DH_INT,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB _mapper-dbscan-inner
 */
DH(X__mapper_dbscan_inner)
{
dharg ret;
ret.dh_int =  C__mapper_dbscan_inner(a[1].dh_idx_ptr, a[2].dh_real, a[3].dh_int, a[4].dh_srg_ptr, a[5].dh_idx_ptr);
return ret;
}

/*
 * DHDOC _mapper-dbscan-inner
 */
DHDOC(K__mapper_dbscan_inner_Rc1b0d783bb4a8447,X__mapper_dbscan_inner,"C__mapper_dbscan_inner",0,0) = {
DH_FUNC(5),
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_REAL,
DH_REAL,
DH_INT,
DH_STR,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_INT,
DH_RETURN,
DH_INT,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB _mapper-dbscan-dm-inner
 */
DH(X__mapper_dbscan_dm_inner)
{
dharg ret;
ret.dh_int =  C__mapper_dbscan_dm_inner(a[1].dh_idx_ptr, a[2].dh_int, a[3].dh_real, a[4].dh_int, a[5].dh_idx_ptr);
return ret;
}

/*
 * DHDOC _mapper-dbscan-dm-inner
 */
DHDOC(K__mapper_dbscan_dm_inner_Rb2ae298176e3bf29,X__mapper_dbscan_dm_inner,"C__mapper_dbscan_dm_inner",0,0) = {
DH_FUNC(5),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_INT,
DH_REAL,
DH_INT,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_INT,
DH_RETURN,
DH_INT,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB mapper-isect-count
 */
DH(X_mapper_isect_count)
{
dharg ret;
ret.dh_int =  C_mapper_isect_count(a[1].dh_idx_ptr, a[2].dh_idx_ptr);
return ret;
}

/*
 * DHDOC mapper-isect-count
 */
DHDOC(K_mapper_isect_count_R611d3d3c1537813d,X_mapper_isect_count,"C_mapper_isect_count",0,0) = {
DH_FUNC(2),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_INT,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_INT,
DH_RETURN,
DH_INT,
DH_END_FUNC,
DH_NIL
};

/*
 * INIT FUNCTION
 */
extern_c void init_cluster(void)
{
 dh_define("_mapper-slink-inner", &K__mapper_slink_inner_Rc7d1a7b1ef9e6368); 
 dh_define("_mapper-slink-dm-inner", &K__mapper_slink_dm_inner_R049aa38524d701d4); 
 dh_define("_mapper-cut-tree-inner", &K__mapper_cut_tree_inner_R2d9ac71aa72b61a1); 
 dh_define("_mapper-cut-tree-dist-inner", &K__mapper_cut_tree_dist_inner_R4b32ed1da585fc27); 
 dh_define("_mapper-dbscan-inner", &K__mapper_dbscan_inner_Rc1b0d783bb4a8447); 
 dh_define("_mapper-dbscan-dm-inner", &K__mapper_dbscan_dm_inner_Rb2ae298176e3bf29); 
 dh_define("mapper-isect-count", &K_mapper_isect_count_R611d3d3c1537813d); 
}

int majver_cluster = 40;
int minver_cluster = 10;


#endif

