/* WARNING: Automatically generated code.
 * This code has been generated by the DH compiler.
 */
#ifdef HAVE_CONFIG_H
# include "lushconf.h"
#endif

/*
 * USER DEFINED HEADERS
 */
 #include "mapper-c.h"
/*
 * LUSH HEADERS
 */
#include "header.h"
#include "dh.h"
#include "idxmac.h"
#include "idxops.h"
#include "check_func.h"



/* ---------------------------------------- */


/*
 * FUNCTION _tsv-dims-inner
 */
extern_c intg C__tsv_dims_inner(struct srg* L1_filename,intg L1_skip_first,struct idx* L1_nr,struct idx* L1_nc)
{
TRACE_PUSH("C__tsv_dims_inner");
{
intg L_Tmp0;
{
intg L2_1_rc;
L2_1_rc = 0;
{
       int nrows = 0, ncols = 0;
       (L2_1_rc) = mapper_tsv_dims((L1_filename)->data, (L1_skip_first), &nrows, &ncols);
       if ((L2_1_rc) == 0) {
         IDX_PTR((L1_nr), int)[0] = nrows;
         IDX_PTR((L1_nc), int)[0] = ncols;
       }
    }
L_Tmp0 = L2_1_rc;
}
TRACE_POP("C__tsv_dims_inner");
return L_Tmp0;
}
}

/*
 * FUNCTION _tsv-read-inner
 */
extern_c intg C__tsv_read_inner(struct srg* L1_filename,intg L1_skip_first,struct idx* L1_data)
{
TRACE_PUSH("C__tsv_read_inner");
{
intg L_Tmp0;
{
intg L2_1_nrows;
intg L2_2_ncols;
intg L2_3_rc;
L2_1_nrows = (L1_data)->dim[0];
L2_2_ncols = (L1_data)->dim[1];
L2_3_rc = 0;
{
       if ((L1_data)->mod[1] != 1)
         error(NIL, "data must be contiguous (mod[1]=1)", NIL);
       (L2_3_rc) = mapper_tsv_read((L1_filename)->data, (L1_skip_first),
                             IDX_PTR((L1_data), double), (L2_1_nrows), (L2_2_ncols));
    }
L_Tmp0 = L2_3_rc;
}
TRACE_POP("C__tsv_read_inner");
return L_Tmp0;
}
}

/* ---------------------------------------- */

#ifndef NOLISP


/*
 * STUB _tsv-dims-inner
 */
DH(X__tsv_dims_inner)
{
dharg ret;
ret.dh_int =  C__tsv_dims_inner(a[1].dh_srg_ptr, a[2].dh_int, a[3].dh_idx_ptr, a[4].dh_idx_ptr);
return ret;
}

/*
 * DHDOC _tsv-dims-inner
 */
DHDOC(K__tsv_dims_inner_Ra8e4b04cf0522170,X__tsv_dims_inner,"C__tsv_dims_inner",0,0) = {
DH_FUNC(4),
DH_STR,
DH_INT,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_INT,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_INT,
DH_RETURN,
DH_INT,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB _tsv-read-inner
 */
DH(X__tsv_read_inner)
{
dharg ret;
ret.dh_int =  C__tsv_read_inner(a[1].dh_srg_ptr, a[2].dh_int, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC _tsv-read-inner
 */
DHDOC(K__tsv_read_inner_R547c544672e08222,X__tsv_read_inner,"C__tsv_read_inner",0,0) = {
DH_FUNC(3),
DH_STR,
DH_INT,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_REAL,
DH_RETURN,
DH_INT,
DH_END_FUNC,
DH_NIL
};

/*
 * INIT FUNCTION
 */
extern_c void init_csvread(void)
{
 dh_define("_tsv-dims-inner", &K__tsv_dims_inner_Ra8e4b04cf0522170); 
 dh_define("_tsv-read-inner", &K__tsv_read_inner_R547c544672e08222); 
}

int majver_csvread = 40;
int minver_csvread = 10;


#endif

