/* WARNING: Automatically generated code.
 * This code has been generated by the DH compiler.
 */
#ifdef HAVE_CONFIG_H
# include "lushconf.h"
#endif

/*
 * USER DEFINED HEADERS
 */
 #include "mapper-c.h"
/*
 * LUSH HEADERS
 */
#include "header.h"
#include "dh.h"
#include "idxmac.h"
#include "idxops.h"
#include "check_func.h"



/* ---------------------------------------- */


/*
 * FUNCTION mapper-distance-matrix
 */
extern_c struct idx* C_mapper_distance_matrix(struct idx* L1_data,struct srg* L1_metric,struct idx* L2_0_matrix,struct srg* L2_0_srg)
{
TRACE_PUSH("C_mapper_distance_matrix");
{
struct idx* L_Tmp0;
{
intg L2_1_n;
intg L2_2_nc;
intg L2_3_dmsz;
struct idx* L2_4_dm;
L2_1_n = (L1_data)->dim[0];
L2_2_nc = (L1_data)->dim[1];
L2_3_dmsz = ((L2_1_n*(L2_1_n-1))/(real)2);
(L2_0_matrix)->srg = L2_0_srg;
Midx_init_dim1(L2_0_matrix, L2_3_dmsz);
RTERR_DIM(L2_0_matrix->dim[0]<=0);
Midx_maclear(L2_0_matrix, real);
L2_4_dm = L2_0_matrix;
{
       if ((L1_data)->mod[1] != 1) {
         error(NIL, "data must be contiguous (mod[1]=1)", NIL);
       }
       metric_fn_t mf = mapper_select_metric((L1_metric)->data);
       if (!mf) error(NIL, "unknown metric", new_string((L1_metric)->data));
       mapper_distance_matrix(IDX_PTR((L1_data), double), (L2_1_n), (L2_2_nc), mf,
                              IDX_PTR((L2_4_dm), double));
    }
L_Tmp0 = L2_4_dm;
}
TRACE_POP("C_mapper_distance_matrix");
return L_Tmp0;
}
}

/* ---------------------------------------- */

#ifndef NOLISP


/*
 * STUB mapper-distance-matrix
 */
DH(X_mapper_distance_matrix)
{
dharg ret;
ret.dh_idx_ptr =  C_mapper_distance_matrix(a[1].dh_idx_ptr, a[2].dh_srg_ptr, a[3].dh_idx_ptr, a[4].dh_srg_ptr);
return ret;
}

/*
 * DHDOC mapper-distance-matrix
 */
DHDOC(K_mapper_distance_matrix_Ra3d9f39abf5f4fdd,X_mapper_distance_matrix,"C_mapper_distance_matrix",0,0) = {
DH_FUNC(2),
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_REAL,
DH_STR,
DH_TEMPS(2),
DH_IDX(DHT_WRITE,1),DH_REAL,
DH_SRG(DHT_WRITE), DH_REAL,
DH_END_TEMPS,
DH_RETURN,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_REAL,
DH_END_FUNC,
DH_NIL
};

/*
 * INIT FUNCTION
 */
extern_c void init_metrics(void)
{
 dh_define("mapper-distance-matrix", &K_mapper_distance_matrix_Ra3d9f39abf5f4fdd); 
}

int majver_metrics = 40;
int minver_metrics = 10;


#endif

